id = "nomi"
name = "Nomi"
version = "0.0.1"
schema_version = 1
authors = ["David Baldwin"]
description = "Syntax highlighting and language server support for the Nomi programming language"

[language_servers.nomi-lsp]
name = "Nomi LSP"
languages = ["Nomi"]

[grammars.nomi]
repository = "https://github.com/nomi-language/tree-sitter-nomi"
rev = "13ef7979a5096d45ddce3d735e50380babfe4334"
