// Code generated by internal/hostgen; DO NOT EDIT.
// Source: internal/hostgen/fixture. Regenerate with `go generate ./internal/hostgen/fixture/ffxadapters`.

package ffxadapters

import (
	"errors"
	"fmt"
	"github.com/nomi-language/nomi/hostadapt"
	"github.com/nomi-language/nomi/internal/hostgen/fixture"
	"github.com/nomi-language/nomi/rt"
	"time"
)

var (
	_ = errors.New
	_ = fmt.Errorf
)

var spec_d0 = &hostadapt.DescSpec{Name: "results.Result", Kind: rt.KindEnum, Variants: []rt.VariantSpec{{Name: "Ok", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotInt}}}, {Name: "Err", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotString}}}}}

var spec_d1 = &hostadapt.DescSpec{Name: "ffx.Point", Kind: rt.KindStruct, Fields: []rt.FieldSpec{{Name: "x", Type: rt.SlotInt}, {Name: "y", Type: rt.SlotInt}}}

var spec_d2 = &hostadapt.DescSpec{Name: "ffx.Tagged", Kind: rt.KindStruct, Fields: []rt.FieldSpec{{Name: "label", Type: rt.SlotString}, {Name: "x", Type: rt.SlotInt}, {Name: "y", Type: rt.SlotInt}, {Name: "small", Type: rt.SlotInt}, {Name: "wide", Type: rt.SlotInt}, {Name: "ratio", Type: rt.SlotFloat}, {Name: "at", Type: rt.SlotRef}, {Name: "wait", Type: rt.SlotRef}, {Name: "raw", Type: rt.SlotBytes}, {Name: "tags", Type: rt.SlotRef}, {Name: "near", Type: rt.SlotRef}}}

var spec_d3 = &hostadapt.DescSpec{Name: "instant.Instant", Kind: rt.KindDistinct, Inner: hostadapt.Slot(rt.SlotInt)}

var spec_d4 = &hostadapt.DescSpec{Name: "duration.Duration", Kind: rt.KindDistinct, Inner: hostadapt.Slot(rt.SlotInt)}

var spec_d5 = &hostadapt.DescSpec{Name: "maybe.Maybe", Kind: rt.KindEnum, Variants: []rt.VariantSpec{{Name: "Some", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotRef}}}, {Name: "None", Shape: rt.VariantBare}}}

var spec_d6 = &hostadapt.DescSpec{Name: "results.Result", Kind: rt.KindEnum, Variants: []rt.VariantSpec{{Name: "Ok", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotRef}}}, {Name: "Err", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotString}}}}}

var spec_d7 = &hostadapt.DescSpec{Name: "ffx.Query", Kind: rt.KindStruct, Fields: []rt.FieldSpec{{Name: "path", Type: rt.SlotString}, {Name: "params", Type: rt.SlotRef}}}

// bound holds the descriptors the adapters build with, resolved once.
type bound struct {
	env *hostadapt.Env
	d0  *rt.TypeDesc
	d1  *rt.TypeDesc
	d2  *rt.TypeDesc
	d3  *rt.TypeDesc
	d4  *rt.TypeDesc
	d5  *rt.TypeDesc
	d6  *rt.TypeDesc
	d7  *rt.TypeDesc
	d8  *rt.TypeDesc
	d9  *rt.TypeDesc
}

// Specs lists the descriptor specs the adapters build with, so an engine can
// link its own descriptors for them before Bind.
func Specs() []*hostadapt.DescSpec {
	return []*hostadapt.DescSpec{
		spec_d0,
		spec_d1,
		spec_d2,
		spec_d3,
		spec_d4,
		spec_d5,
		spec_d6,
		spec_d7,
	}
}

// Names lists every binding this file adapts, in table order.
func Names() []string {
	return []string{
		"ffx.apply",
		"ffx.attempt",
		"ffx.biggest",
		"ffx.box_value",
		"ffx.check",
		"ffx.echo",
		"ffx.flip",
		"ffx.halve",
		"ffx.later",
		"ffx.mirror",
		"ffx.narrow",
		"ffx.negate",
		"ffx.new_box",
		"ffx.nothing",
		"ffx.nothing_or_fail",
		"ffx.octets",
		"ffx.points",
		"ffx.query",
		"ffx.run",
		"ffx.shout",
		"ffx.sizes",
		"ffx.triple",
		"ffx.triple_or_fail",
		"ffx.visit",
		"ffx.zero_time",
	}
}

// Bind resolves every descriptor through env and answers the adapters by
// binding name.
func Bind(env *hostadapt.Env) (map[string]hostadapt.Func, error) {
	b := &bound{env: env}
	var err error
	if b.d0, err = env.Desc(spec_d0); err != nil {
		return nil, err
	}
	if b.d1, err = env.Desc(spec_d1); err != nil {
		return nil, err
	}
	if b.d2, err = env.Desc(spec_d2); err != nil {
		return nil, err
	}
	if b.d3, err = env.Desc(spec_d3); err != nil {
		return nil, err
	}
	if b.d4, err = env.Desc(spec_d4); err != nil {
		return nil, err
	}
	if b.d5, err = env.Desc(spec_d5); err != nil {
		return nil, err
	}
	if b.d6, err = env.Desc(spec_d6); err != nil {
		return nil, err
	}
	if b.d7, err = env.Desc(spec_d7); err != nil {
		return nil, err
	}
	b.d8 = rt.TupleDesc(rt.SlotInt, rt.SlotString, rt.SlotBool)
	b.d9 = rt.TupleDesc(rt.SlotInt, rt.SlotString)
	return map[string]hostadapt.Func{
		"ffx.apply":           b.fn1,
		"ffx.attempt":         b.fn5,
		"ffx.biggest":         b.fn8,
		"ffx.box_value":       b.fn10,
		"ffx.check":           b.fn12,
		"ffx.echo":            b.fn18,
		"ffx.flip":            b.fn36,
		"ffx.halve":           b.fn39,
		"ffx.later":           b.fn42,
		"ffx.mirror":          b.fn43,
		"ffx.narrow":          b.fn44,
		"ffx.negate":          b.fn53,
		"ffx.new_box":         b.fn54,
		"ffx.nothing":         b.fn56,
		"ffx.nothing_or_fail": b.fn57,
		"ffx.octets":          b.fn58,
		"ffx.points":          b.fn61,
		"ffx.query":           b.fn63,
		"ffx.run":             b.fn67,
		"ffx.shout":           b.fn69,
		"ffx.sizes":           b.fn72,
		"ffx.triple":          b.fn75,
		"ffx.triple_or_fail":  b.fn76,
		"ffx.visit":           b.fn77,
		"ffx.zero_time":       b.fn79,
	}, nil
}

// in3 reads a Int as Go int64.
func (b *bound) in3(fr *rt.Frame, v rt.Value) (out int64, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return int64(x), nil
}

// in2 reads a (Int) -> Int as Go func(int64) int64.
func (b *bound) in2(fr *rt.Frame, v rt.Value) (out func(int64) int64, err error) {
	if v == nil {
		return out, fmt.Errorf("expected a function, got nil")
	}
	return func(p0 int64) int64 {
		res, err := b.env.Call(fr, v, []rt.Value{int64(p0)})
		if err != nil {
			panic(hostadapt.CallbackFailure(err, "func(int64) int64"))
		}
		y, err := b.in3(fr, res)
		if err != nil {
			panic(hostadapt.CallbackFailure(err, "func(int64) int64"))
		}
		return y
	}, nil
}

// out4 builds a Int from Go int64.
func (b *bound) out4(v int64) (rt.Value, error) {
	return int64(v), nil
}

// fn1 adapts ffx.apply: apply(f: (Int) -> Int, x: Int): Int
func (b *bound) fn1(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.apply", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.apply", 2, len(args))
	}
	a0, err := b.in2(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.apply", 0, err)
	}
	a1, err := b.in3(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.apply", 1, err)
	}
	r0 := fixture.Apply(a0, a1)
	v0, err := b.out4(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in6 reads a (String) -> Result<Int, String> as Go func(string) (int64, error).
func (b *bound) in6(fr *rt.Frame, v rt.Value) (out func(string) (int64, error), err error) {
	if v == nil {
		return out, fmt.Errorf("expected a function, got nil")
	}
	return func(p0 string) (int64, error) {
		res, err := b.env.Call(fr, v, []rt.Value{string(p0)})
		if err != nil {
			var z0 int64
			return z0, err
		}
		r, tag, err := hostadapt.Variant(res, "results.Result")
		if err != nil {
			var z0 int64
			return z0, err
		}
		if tag == "Err" {
			msg, ok := hostadapt.Payload(r).(string)
			if !ok {
				var z0 int64
				return z0, fmt.Errorf("unmarshal Result::Err: expected String payload, got %T", hostadapt.Payload(r))
			}
			var z0 int64
			return z0, errors.New(msg)
		}
		if tag != "Ok" {
			var z0 int64
			return z0, fmt.Errorf("unknown Result variant %q", tag)
		}
		y, err := b.in3(fr, hostadapt.Payload(r))
		if err != nil {
			var z0 int64
			return z0, err
		}
		return y, nil
	}, nil
}

// in7 reads a String as Go string.
func (b *bound) in7(fr *rt.Frame, v rt.Value) (out string, err error) {
	x, ok := v.(string)
	if !ok {
		return out, hostadapt.Want("String", v)
	}
	return string(x), nil
}

// fn5 adapts ffx.attempt: attempt(f: (String) -> Result<Int, String>, s: String): Result<Int, String>
func (b *bound) fn5(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.attempt", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.attempt", 2, len(args))
	}
	a0, err := b.in6(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.attempt", 0, err)
	}
	a1, err := b.in7(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.attempt", 1, err)
	}
	r0, e := fixture.Attempt(a0, a1)
	if e != nil {
		rec := b.d0.NewVariant(1)
		rec.S[0] = e.Error()
		return rec, nil
	}
	v0, err := b.out4(r0)
	if err != nil {
		return nil, err
	}
	ok := b.d0.NewVariant(0)
	ok.W[0] = rt.IntWord(v0.(int64))
	return ok, nil
}

// out9 builds a Int from Go uint64.
func (b *bound) out9(v uint64) (rt.Value, error) {
	x, err := hostadapt.FromUnsigned(v, "uint64")
	if err != nil {
		return nil, err
	}
	return x, nil
}

// fn8 adapts ffx.biggest: biggest(): Int
func (b *bound) fn8(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.biggest", &err)
	if len(args) != 0 {
		return nil, hostadapt.Arity("ffx.biggest", 0, len(args))
	}
	r0 := fixture.Biggest()
	v0, err := b.out9(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in11 reads a Box as Go *fixture.Box.
func (b *bound) in11(fr *rt.Frame, v rt.Value) (out *fixture.Box, err error) {
	h, err := hostadapt.Handle(v, "ffx.Box")
	if err != nil {
		return out, err
	}
	p, ok := h.(*fixture.Box)
	if !ok {
		return out, fmt.Errorf("ffx.Box handle holds %T, not *fixture.Box", h)
	}
	return p, nil
}

// fn10 adapts ffx.box_value: box_value(b: Box): Int
func (b *bound) fn10(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.box_value", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.box_value", 1, len(args))
	}
	a0, err := b.in11(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.box_value", 0, err)
	}
	r0 := fixture.BoxValue(a0)
	v0, err := b.out4(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// out14 builds a Point from Go fixture.Point.
func (b *bound) out14(v fixture.Point) (rt.Value, error) {
	r := b.d1.New()
	r.W[0] = rt.IntWord(int64(v.X))
	r.W[1] = rt.IntWord(int64(v.Y))
	return r, nil
}

// in15 reads a Bool as Go bool.
func (b *bound) in15(fr *rt.Frame, v rt.Value) (out bool, err error) {
	x, ok := v.(bool)
	if !ok {
		return out, hostadapt.Want("Bool", v)
	}
	return bool(x), nil
}

// in13 reads a (Point) -> Bool as Go func(fixture.Point) bool.
func (b *bound) in13(fr *rt.Frame, v rt.Value) (out func(fixture.Point) bool, err error) {
	if v == nil {
		return out, fmt.Errorf("expected a function, got nil")
	}
	return func(p0 fixture.Point) bool {
		x0, err := b.out14(p0)
		if err != nil {
			panic(fmt.Sprintf("Nomi callback arg 0: %v", err))
		}
		res, err := b.env.Call(fr, v, []rt.Value{x0})
		if err != nil {
			panic(hostadapt.CallbackFailure(err, "func(fixture.Point) bool"))
		}
		y, err := b.in15(fr, res)
		if err != nil {
			panic(hostadapt.CallbackFailure(err, "func(fixture.Point) bool"))
		}
		return y
	}, nil
}

// in16 reads a Point as Go fixture.Point.
func (b *bound) in16(fr *rt.Frame, v rt.Value) (out fixture.Point, err error) {
	r, err := hostadapt.Record(v, "ffx.Point")
	if err != nil {
		return out, err
	}
	{
		x, err := hostadapt.IntField(r, b.d1, 0, 0, "x")
		if err != nil {
			return out, err
		}
		out.X = int64(x)
	}
	{
		x, err := hostadapt.IntField(r, b.d1, 1, 1, "y")
		if err != nil {
			return out, err
		}
		out.Y = int64(x)
	}
	return out, nil
}

// out17 builds a Bool from Go bool.
func (b *bound) out17(v bool) (rt.Value, error) {
	return bool(v), nil
}

// fn12 adapts ffx.check: check(f: (Point) -> Bool, p: Point): Bool
func (b *bound) fn12(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.check", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.check", 2, len(args))
	}
	a0, err := b.in13(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.check", 0, err)
	}
	a1, err := b.in16(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.check", 1, err)
	}
	r0 := fixture.Check(a0, a1)
	v0, err := b.out17(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in20 reads a Instant as Go time.Time.
func (b *bound) in20(fr *rt.Frame, v rt.Value) (out time.Time, err error) {
	r, err := hostadapt.Record(v, "instant.Instant")
	if err != nil {
		return out, err
	}
	x, err := hostadapt.IntField(r, b.d3, 0, 0, "")
	if err != nil {
		return out, err
	}
	return time.Unix(0, x).UTC(), nil
}

// in21 reads a Duration as Go time.Duration.
func (b *bound) in21(fr *rt.Frame, v rt.Value) (out time.Duration, err error) {
	r, err := hostadapt.Record(v, "duration.Duration")
	if err != nil {
		return out, err
	}
	x, err := hostadapt.IntField(r, b.d4, 0, 0, "")
	if err != nil {
		return out, err
	}
	return time.Duration(x), nil
}

// in22 reads a List<String> as Go []string.
func (b *bound) in22(fr *rt.Frame, v rt.Value) (out []string, err error) {
	xs, err := hostadapt.List(v)
	if err != nil {
		return out, err
	}
	out = make([]string, 0, hostadapt.Len(xs))
	i := 0
	for c := xs; c != nil; c = c.Tail {
		e, err := b.in7(fr, c.Head)
		if err != nil {
			return nil, fmt.Errorf("index %d: %w", i, err)
		}
		out = append(out, e)
		i++
	}
	return out, nil
}

// in23 reads a Maybe<Point> as Go *fixture.Point.
func (b *bound) in23(fr *rt.Frame, v rt.Value) (out *fixture.Point, err error) {
	r, tag, err := hostadapt.Variant(v, "maybe.Maybe")
	if err != nil {
		return out, err
	}
	switch tag {
	case "None":
		return nil, nil
	case "Some":
		x, err := b.in16(fr, hostadapt.Payload(r))
		if err != nil {
			return nil, fmt.Errorf("Some: %w", err)
		}
		return &x, nil
	}
	return nil, fmt.Errorf("unmarshal Maybe: unknown variant %q", tag)
}

// in19 reads a Tagged as Go fixture.Tagged.
func (b *bound) in19(fr *rt.Frame, v rt.Value) (out fixture.Tagged, err error) {
	r, err := hostadapt.Record(v, "ffx.Tagged")
	if err != nil {
		return out, err
	}
	{
		x, err := hostadapt.StringField(r, b.d2, 0, 0, "label")
		if err != nil {
			return out, err
		}
		out.Name = string(x)
	}
	{
		x, err := hostadapt.IntField(r, b.d2, 1, 0, "x")
		if err != nil {
			return out, err
		}
		out.Point.X = int64(x)
	}
	{
		x, err := hostadapt.IntField(r, b.d2, 2, 1, "y")
		if err != nil {
			return out, err
		}
		out.Point.Y = int64(x)
	}
	{
		x, err := hostadapt.IntField(r, b.d2, 3, 2, "small")
		if err != nil {
			return out, err
		}
		y, err := hostadapt.ToSigned[int8](x, "int8")
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "small", err)
		}
		out.Small = y
	}
	{
		x, err := hostadapt.IntField(r, b.d2, 4, 3, "wide")
		if err != nil {
			return out, err
		}
		y, err := hostadapt.ToUnsigned[uint32](x, "uint32")
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "wide", err)
		}
		out.Wide = y
	}
	{
		x, err := hostadapt.FloatField(r, b.d2, 5, 4, "ratio")
		if err != nil {
			return out, err
		}
		y, err := hostadapt.ToFloat32[float32](x, "float32")
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "ratio", err)
		}
		out.Ratio = y
	}
	{
		x, err := hostadapt.RefField(r, b.d2, 6, 0, "at")
		if err != nil {
			return out, err
		}
		y, err := b.in20(fr, x)
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "at", err)
		}
		out.When = y
	}
	{
		x, err := hostadapt.RefField(r, b.d2, 7, 1, "wait")
		if err != nil {
			return out, err
		}
		y, err := b.in21(fr, x)
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "wait", err)
		}
		out.Wait = y
	}
	{
		x, err := hostadapt.BytesField(r, b.d2, 8, 1, "raw")
		if err != nil {
			return out, err
		}
		out.Raw = []uint8(x)
	}
	{
		x, err := hostadapt.RefField(r, b.d2, 9, 2, "tags")
		if err != nil {
			return out, err
		}
		y, err := b.in22(fr, x)
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "tags", err)
		}
		out.Tags = y
	}
	{
		x, err := hostadapt.RefField(r, b.d2, 10, 3, "near")
		if err != nil {
			return out, err
		}
		y, err := b.in23(fr, x)
		if err != nil {
			return out, fmt.Errorf("field %q: %w", "near", err)
		}
		out.Near = y
	}
	return out, nil
}

// out26 builds a Instant from Go time.Time.
func (b *bound) out26(v time.Time) (rt.Value, error) {
	r := b.d3.New()
	n, err := hostadapt.InstantNanos(v)
	if err != nil {
		return nil, err
	}
	r.W[0] = rt.IntWord(n)
	return r, nil
}

// out28 builds a Duration from Go time.Duration.
func (b *bound) out28(v time.Duration) (rt.Value, error) {
	r := b.d4.New()
	r.W[0] = rt.IntWord(int64(v))
	return r, nil
}

// out31 builds a String from Go string.
func (b *bound) out31(v string) (rt.Value, error) {
	return string(v), nil
}

// out30 builds a List<String> from Go []string.
func (b *bound) out30(v []string) (rt.Value, error) {
	var xs *rt.List[any]
	for i := len(v) - 1; i >= 0; i-- {
		x, err := b.out31(v[i])
		if err != nil {
			return nil, fmt.Errorf("index %d: %w", i, err)
		}
		xs = rt.Cons[any](x, xs)
	}
	return xs, nil
}

// out33 builds a Maybe<Point> from Go *fixture.Point.
func (b *bound) out33(v *fixture.Point) (rt.Value, error) {
	if v == nil {
		return b.d5.NewVariant(1), nil
	}
	r := b.d5.NewVariant(0)
	w34, err := b.out14(*v)
	if err != nil {
		return nil, err
	}
	r.R[0] = w34
	return r, nil
}

// out24 builds a Tagged from Go fixture.Tagged.
func (b *bound) out24(v fixture.Tagged) (rt.Value, error) {
	r := b.d2.New()
	r.S[0] = string(v.Name)
	r.W[0] = rt.IntWord(int64(v.Point.X))
	r.W[1] = rt.IntWord(int64(v.Point.Y))
	r.W[2] = rt.IntWord(int64(v.Small))
	w25, err := hostadapt.FromUnsigned(v.Wide, "uint32")
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "wide", err)
	}
	r.W[3] = rt.IntWord(w25)
	r.W[4] = rt.FloatWord(float64(v.Ratio))
	w27, err := b.out26(v.When)
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "at", err)
	}
	r.R[0] = w27
	w29, err := b.out28(v.Wait)
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "wait", err)
	}
	r.R[1] = w29
	r.S[1] = string(rt.Bytes(v.Raw))
	w32, err := b.out30(v.Tags)
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "tags", err)
	}
	r.R[2] = w32
	w35, err := b.out33(v.Near)
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "near", err)
	}
	r.R[3] = w35
	return r, nil
}

// fn18 adapts ffx.echo: echo(t: Tagged): Tagged
func (b *bound) fn18(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.echo", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.echo", 1, len(args))
	}
	a0, err := b.in19(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.echo", 0, err)
	}
	r0 := fixture.Echo(a0)
	v0, err := b.out24(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in37 reads a Byte as Go uint8.
func (b *bound) in37(fr *rt.Frame, v rt.Value) (out uint8, err error) {
	x, ok := v.(rt.Byte)
	if !ok {
		return out, hostadapt.Want("Byte", v)
	}
	return uint8(x), nil
}

// out38 builds a Byte from Go uint8.
func (b *bound) out38(v uint8) (rt.Value, error) {
	return rt.Byte(v), nil
}

// fn36 adapts ffx.flip: flip(b: Byte): Byte
func (b *bound) fn36(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.flip", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.flip", 1, len(args))
	}
	a0, err := b.in37(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.flip", 0, err)
	}
	r0 := fixture.Flip(a0)
	v0, err := b.out38(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in40 reads a Float as Go float32.
func (b *bound) in40(fr *rt.Frame, v rt.Value) (out float32, err error) {
	x, ok := v.(float64)
	if !ok {
		return out, hostadapt.Want("Float", v)
	}
	return hostadapt.ToFloat32[float32](x, "float32")
}

// out41 builds a Float from Go float32.
func (b *bound) out41(v float32) (rt.Value, error) {
	return float64(v), nil
}

// fn39 adapts ffx.halve: halve(f: Float): Float
func (b *bound) fn39(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.halve", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.halve", 1, len(args))
	}
	a0, err := b.in40(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.halve", 0, err)
	}
	r0 := fixture.Halve(a0)
	v0, err := b.out41(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// fn42 adapts ffx.later: later(t: Instant, by: Duration): Instant
func (b *bound) fn42(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.later", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.later", 2, len(args))
	}
	a0, err := b.in20(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.later", 0, err)
	}
	a1, err := b.in21(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.later", 1, err)
	}
	r0 := fixture.Later(a0, a1)
	v0, err := b.out26(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// fn43 adapts ffx.mirror: mirror(p: Maybe<Point>): Maybe<Point>
func (b *bound) fn43(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.mirror", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.mirror", 1, len(args))
	}
	a0, err := b.in23(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.mirror", 0, err)
	}
	r0 := fixture.Mirror(a0)
	v0, err := b.out33(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in45 reads a Int as Go int8.
func (b *bound) in45(fr *rt.Frame, v rt.Value) (out int8, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToSigned[int8](x, "int8")
}

// in46 reads a Int as Go int16.
func (b *bound) in46(fr *rt.Frame, v rt.Value) (out int16, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToSigned[int16](x, "int16")
}

// in47 reads a Int as Go int32.
func (b *bound) in47(fr *rt.Frame, v rt.Value) (out int32, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToSigned[int32](x, "int32")
}

// in48 reads a Int as Go int.
func (b *bound) in48(fr *rt.Frame, v rt.Value) (out int, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToSigned[int](x, "int")
}

// in49 reads a Int as Go uint.
func (b *bound) in49(fr *rt.Frame, v rt.Value) (out uint, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToUnsigned[uint](x, "uint")
}

// in50 reads a Int as Go uint16.
func (b *bound) in50(fr *rt.Frame, v rt.Value) (out uint16, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToUnsigned[uint16](x, "uint16")
}

// in51 reads a Int as Go uint32.
func (b *bound) in51(fr *rt.Frame, v rt.Value) (out uint32, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToUnsigned[uint32](x, "uint32")
}

// in52 reads a Int as Go uint64.
func (b *bound) in52(fr *rt.Frame, v rt.Value) (out uint64, err error) {
	x, ok := v.(int64)
	if !ok {
		return out, hostadapt.Want("Int", v)
	}
	return hostadapt.ToUnsigned[uint64](x, "uint64")
}

// fn44 adapts ffx.narrow: narrow(a: Int, b: Int, c: Int, d: Int, e: Int, f: Int, g: Int, h: Int): Int
func (b *bound) fn44(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.narrow", &err)
	if len(args) != 8 {
		return nil, hostadapt.Arity("ffx.narrow", 8, len(args))
	}
	a0, err := b.in45(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 0, err)
	}
	a1, err := b.in46(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 1, err)
	}
	a2, err := b.in47(fr, args[2])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 2, err)
	}
	a3, err := b.in48(fr, args[3])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 3, err)
	}
	a4, err := b.in49(fr, args[4])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 4, err)
	}
	a5, err := b.in50(fr, args[5])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 5, err)
	}
	a6, err := b.in51(fr, args[6])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 6, err)
	}
	a7, err := b.in52(fr, args[7])
	if err != nil {
		return nil, hostadapt.Arg("ffx.narrow", 7, err)
	}
	r0 := fixture.Narrow(a0, a1, a2, a3, a4, a5, a6, a7)
	v0, err := b.out4(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// fn53 adapts ffx.negate: negate(b: Bool): Bool
func (b *bound) fn53(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.negate", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.negate", 1, len(args))
	}
	a0, err := b.in15(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.negate", 0, err)
	}
	r0 := fixture.Negate(a0)
	v0, err := b.out17(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// out55 builds a Box from Go *fixture.Box.
func (b *bound) out55(v *fixture.Box) (rt.Value, error) {
	return rt.HostHandle{TypeName: "ffx.Box", Value: v}, nil
}

// fn54 adapts ffx.new_box: new_box(n: Int): Box
func (b *bound) fn54(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.new_box", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.new_box", 1, len(args))
	}
	a0, err := b.in3(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.new_box", 0, err)
	}
	r0 := fixture.NewBox(a0)
	v0, err := b.out55(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// fn56 adapts ffx.nothing: nothing(): Unit
func (b *bound) fn56(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.nothing", &err)
	if len(args) != 0 {
		return nil, hostadapt.Arity("ffx.nothing", 0, len(args))
	}
	fixture.Nothing()
	return rt.Unit{}, nil
}

// fn57 adapts ffx.nothing_or_fail: nothing_or_fail(fail: Bool): Result<Unit, String>
func (b *bound) fn57(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.nothing_or_fail", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.nothing_or_fail", 1, len(args))
	}
	a0, err := b.in15(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.nothing_or_fail", 0, err)
	}
	e := fixture.NothingOrFail(a0)
	if e != nil {
		rec := b.d6.NewVariant(1)
		rec.S[0] = e.Error()
		return rec, nil
	}
	ok := b.d6.NewVariant(0)
	ok.R[0] = rt.Unit{}
	return ok, nil
}

// in59 reads a Bytes as Go []fixture.MyByte.
func (b *bound) in59(fr *rt.Frame, v rt.Value) (out []fixture.MyByte, err error) {
	x, ok := v.(rt.Bytes)
	if !ok {
		return out, hostadapt.Want("Bytes", v)
	}
	return func() []fixture.MyByte {
		out := make([]fixture.MyByte, len(x))
		for i := range len(x) {
			out[i] = fixture.MyByte(x[i])
		}
		return out
	}(), nil
}

// out60 builds a Bytes from Go []fixture.MyByte.
func (b *bound) out60(v []fixture.MyByte) (rt.Value, error) {
	return func() rt.Bytes {
		out := make([]byte, len(v))
		for i := range len(v) {
			out[i] = byte(v[i])
		}
		return rt.Bytes(out)
	}(), nil
}

// fn58 adapts ffx.octets: octets(b: Bytes): Bytes
func (b *bound) fn58(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.octets", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.octets", 1, len(args))
	}
	a0, err := b.in59(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.octets", 0, err)
	}
	r0 := fixture.Octets(a0)
	v0, err := b.out60(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// out62 builds a List<Point> from Go []fixture.Point.
func (b *bound) out62(v []fixture.Point) (rt.Value, error) {
	var xs *rt.List[any]
	for i := len(v) - 1; i >= 0; i-- {
		x, err := b.out14(v[i])
		if err != nil {
			return nil, fmt.Errorf("index %d: %w", i, err)
		}
		xs = rt.Cons[any](x, xs)
	}
	return xs, nil
}

// fn61 adapts ffx.points: points(n: Int): List<Point>
func (b *bound) fn61(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.points", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.points", 1, len(args))
	}
	a0, err := b.in3(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.points", 0, err)
	}
	r0 := fixture.Points(a0)
	v0, err := b.out62(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// out65 builds a Map<String, List<String>> from Go map[string][]string.
func (b *bound) out65(v map[string][]string) (rt.Value, error) {
	conv := make([]rt.MapEntry[any, any], 0, len(v))
	for gk, gv := range v {
		k, err := b.out31(gk)
		if err != nil {
			return nil, fmt.Errorf("key %v: %w", gk, err)
		}
		x, err := b.out30(gv)
		if err != nil {
			return nil, fmt.Errorf("value at %v: %w", gk, err)
		}
		conv = append(conv, rt.MapEntry[any, any]{Key: k, Val: x})
	}
	return rt.MapOf(rt.Hash, rt.Equal, conv), nil
}

// out64 builds a Query from Go fixture.Query.
func (b *bound) out64(v fixture.Query) (rt.Value, error) {
	r := b.d7.New()
	r.S[0] = string(v.Path)
	w66, err := b.out65(v.Params)
	if err != nil {
		return nil, fmt.Errorf("field %q: %w", "params", err)
	}
	r.R[0] = w66
	return r, nil
}

// fn63 adapts ffx.query: query(path: String, words: List<String>): Query
func (b *bound) fn63(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.query", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.query", 2, len(args))
	}
	a0, err := b.in7(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.query", 0, err)
	}
	a1, err := b.in22(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.query", 1, err)
	}
	r0 := fixture.MakeQuery(a0, a1)
	v0, err := b.out64(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in68 reads a () -> Result<Unit, String> as Go func() error.
func (b *bound) in68(fr *rt.Frame, v rt.Value) (out func() error, err error) {
	if v == nil {
		return out, fmt.Errorf("expected a function, got nil")
	}
	return func() error {
		res, err := b.env.Call(fr, v, []rt.Value{})
		if err != nil {
			return err
		}
		r, tag, err := hostadapt.Variant(res, "results.Result")
		if err != nil {
			return err
		}
		if tag == "Err" {
			msg, ok := hostadapt.Payload(r).(string)
			if !ok {
				return fmt.Errorf("unmarshal Result::Err: expected String payload, got %T", hostadapt.Payload(r))
			}
			return errors.New(msg)
		}
		if tag != "Ok" {
			return fmt.Errorf("unknown Result variant %q", tag)
		}
		return nil
	}, nil
}

// fn67 adapts ffx.run: run(f: () -> Result<Unit, String>): Result<Unit, String>
func (b *bound) fn67(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.run", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.run", 1, len(args))
	}
	a0, err := b.in68(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.run", 0, err)
	}
	e := fixture.Run(a0)
	if e != nil {
		rec := b.d6.NewVariant(1)
		rec.S[0] = e.Error()
		return rec, nil
	}
	ok := b.d6.NewVariant(0)
	ok.R[0] = rt.Unit{}
	return ok, nil
}

// in70 reads a String as Go fixture.Label.
func (b *bound) in70(fr *rt.Frame, v rt.Value) (out fixture.Label, err error) {
	x, ok := v.(string)
	if !ok {
		return out, hostadapt.Want("String", v)
	}
	return fixture.Label(x), nil
}

// out71 builds a String from Go fixture.Label.
func (b *bound) out71(v fixture.Label) (rt.Value, error) {
	return string(v), nil
}

// fn69 adapts ffx.shout: shout(s: String): String
func (b *bound) fn69(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.shout", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.shout", 1, len(args))
	}
	a0, err := b.in70(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.shout", 0, err)
	}
	r0 := fixture.Shout(a0)
	v0, err := b.out71(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// in73 reads a Map<String, List<String>> as Go map[string][]string.
func (b *bound) in73(fr *rt.Frame, v rt.Value) (out map[string][]string, err error) {
	m, ok := v.(rt.Map[any, any])
	if !ok {
		return out, hostadapt.Want("Map<String, List<String>>", v)
	}
	ents := rt.MapEntries(m)
	out = make(map[string][]string, len(ents))
	for i, e := range ents {
		k, err := b.in7(fr, e.Key)
		if err != nil {
			return nil, fmt.Errorf("key %d: %w", i, err)
		}
		x, err := b.in22(fr, e.Val)
		if err != nil {
			return nil, fmt.Errorf("value %d: %w", i, err)
		}
		out[k] = x
	}
	return out, nil
}

// out74 builds a Map<String, Int> from Go map[string]int64.
func (b *bound) out74(v map[string]int64) (rt.Value, error) {
	conv := make([]rt.MapEntry[any, any], 0, len(v))
	for gk, gv := range v {
		k, err := b.out31(gk)
		if err != nil {
			return nil, fmt.Errorf("key %v: %w", gk, err)
		}
		x, err := b.out4(gv)
		if err != nil {
			return nil, fmt.Errorf("value at %v: %w", gk, err)
		}
		conv = append(conv, rt.MapEntry[any, any]{Key: k, Val: x})
	}
	return rt.MapOf(rt.Hash, rt.Equal, conv), nil
}

// fn72 adapts ffx.sizes: sizes(m: Map<String, List<String>>): Map<String, Int>
func (b *bound) fn72(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.sizes", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.sizes", 1, len(args))
	}
	a0, err := b.in73(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.sizes", 0, err)
	}
	r0 := fixture.Sizes(a0)
	v0, err := b.out74(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}

// fn75 adapts ffx.triple: triple(n: Int): (Int, String, Bool)
func (b *bound) fn75(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.triple", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.triple", 1, len(args))
	}
	a0, err := b.in3(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.triple", 0, err)
	}
	r0, r1, r2 := fixture.Triple(a0)
	tup := b.d8.New()
	tup.W[0] = rt.IntWord(int64(r0))
	tup.S[0] = string(r1)
	tup.W[1] = rt.BoolWord(bool(r2))
	return tup, nil
}

// fn76 adapts ffx.triple_or_fail: triple_or_fail(n: Int): Result<(Int, String), String>
func (b *bound) fn76(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.triple_or_fail", &err)
	if len(args) != 1 {
		return nil, hostadapt.Arity("ffx.triple_or_fail", 1, len(args))
	}
	a0, err := b.in3(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.triple_or_fail", 0, err)
	}
	r0, r1, e := fixture.TripleOrFail(a0)
	if e != nil {
		rec := b.d6.NewVariant(1)
		rec.S[0] = e.Error()
		return rec, nil
	}
	tup := b.d9.New()
	tup.W[0] = rt.IntWord(int64(r0))
	tup.S[0] = string(r1)
	ok := b.d6.NewVariant(0)
	ok.R[0] = tup
	return ok, nil
}

// in78 reads a (Int) -> Unit as Go func(int64).
func (b *bound) in78(fr *rt.Frame, v rt.Value) (out func(int64), err error) {
	if v == nil {
		return out, fmt.Errorf("expected a function, got nil")
	}
	return func(p0 int64) {
		res, err := b.env.Call(fr, v, []rt.Value{int64(p0)})
		if err != nil {
			panic(hostadapt.CallbackFailure(err, "func(int64)"))
		}
		_ = res
	}, nil
}

// fn77 adapts ffx.visit: visit(f: (Int) -> Unit, n: Int): Unit
func (b *bound) fn77(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.visit", &err)
	if len(args) != 2 {
		return nil, hostadapt.Arity("ffx.visit", 2, len(args))
	}
	a0, err := b.in78(fr, args[0])
	if err != nil {
		return nil, hostadapt.Arg("ffx.visit", 0, err)
	}
	a1, err := b.in3(fr, args[1])
	if err != nil {
		return nil, hostadapt.Arg("ffx.visit", 1, err)
	}
	fixture.Visit(a0, a1)
	return rt.Unit{}, nil
}

// fn79 adapts ffx.zero_time: zero_time(): Instant
func (b *bound) fn79(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {
	defer hostadapt.Recover("ffx.zero_time", &err)
	if len(args) != 0 {
		return nil, hostadapt.Arity("ffx.zero_time", 0, len(args))
	}
	r0 := fixture.ZeroTime()
	v0, err := b.out26(r0)
	if err != nil {
		return nil, err
	}
	return v0, nil
}
