name = "Nomi"
grammar = "nomi"
path_suffixes = ["nomi"]
first_line_pattern = '^#!.*\bnomi\b'
line_comments = ["/// ", "//! ", "// "]
tab_size = 4
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
]
