// Code generated by nomi — DO NOT EDIT.
// Wrapper template hash: 4e3a8f5a12f1
// Wrapper module imports project-local FFI through go.mod replace.
// Source project: /abs/project
package main

import (
	stdfmt "fmt"
	stdos "os"
	stdstrconv "strconv"

	stdcontext "context"
	errors "errors"
	fmt "fmt"
	sqlite "github.com/foo/sqlite"
	hostadapt "github.com/nomi-language/nomi/hostadapt"
	rt "github.com/nomi-language/nomi/rt"
	nomivmhost "github.com/nomi-language/nomi/vmhost"
)

const ffiTestResultMarker = "__NOMI_FFI_TEST_RESULT"
const imageUsesCompilerMarker = "__NOMI_IMAGE_USES_COMPILER"
const wrapperModeFlag = "--nomi-wrapper-mode"

func main() {
	mode := ""
	targetPath := ""
	extraArgs := []string{}
	if len(stdos.Args) >= 4 && stdos.Args[1] == wrapperModeFlag {
		mode = stdos.Args[2]
		targetPath = stdos.Args[3]
		extraArgs = stdos.Args[4:]
		stdos.Args = []string{stdos.Args[0]}
	}
	if mode == "" || targetPath == "" {
		stdfmt.Fprintln(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode <check|vmrun|vmtest> <entry.nomi> [line]")
		stdos.Exit(1)
	}
	// ffirun launches the compiled wrapper from WrapperDir so every mode starts
	// from the same generated environment. The USER expects their original cwd
	// to survive (relative file paths in user code, e.g. sqlite.open("tasks.db"),
	// should resolve where they ran nomi, not in the FFI build cache). Restore it
	// from the env var ffirun set before any user code reaches os.Getwd.
	if cwd := stdos.Getenv("NOMI_FFIRUN_USER_CWD"); cwd != "" {
		if err := stdos.Chdir(cwd); err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi %s: restoring user cwd %q: %v\n", mode, cwd, err)
			stdos.Exit(1)
		}
	}
	// 'nomi test --format json' passes the format after the line. Its stdout
	// carries only report records, so a test's own output goes to stderr.
	testFormat := nomivmhost.TestFormatText
	if mode == "vmtest" && len(extraArgs) > 1 {
		format, err := nomivmhost.ParseTestFormat(extraArgs[1])
		if err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi test: %v\n", err)
			stdos.Exit(1)
		}
		testFormat = format
	}
	switch mode {
	case "check":
		checkProgramVM(targetPath)
	case "vmrun":
		runProgramVM(targetPath, extraArgs)
	case "vmtest":
		runTestFileVM(targetPath, extraArgs, testFormat)
	case "vmimage":
		buildImageVM(targetPath, extraArgs)
	default:
		stdfmt.Fprintf(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode <check|vmrun|vmtest> <entry.nomi> [line]\n")
		stdos.Exit(1)
	}
}

// The Go symbols the project binds, referenced here so the Go compiler checks
// each one exists (and reports a missing one at its Nomi declaration) whether
// or not the adapter generator could adapt it.
var (
//line /abs/project/sqlite.nomi:3
	_ = (*sqlite.Conn)(nil)
//line /abs/project/sqlite.nomi:5
	_ = sqlite.OpenRaw
)

// checkProgramVM, runProgramVM and runTestFileVM are the wrapper's modes: nomi
// check's, nomi run's and nomi test's. The VM calls the project's bindings
// through the adapters generated below (nomiHostTable).
func checkProgramVM(entryPath string) {
	if err := nomivmhost.Check(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath))); err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
}

func runProgramVM(entryPath string, args []string) {
	p, err := nomivmhost.Load(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath)), nomivmhost.WithInput(stdos.Stdin))
	if err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
	if err := p.RequireMain("run"); err != nil {
		stdfmt.Fprintf(stdos.Stderr, "nomi run: %v\n", err)
		stdos.Exit(1)
	}
	if err := p.Run(stdcontext.Background(), stdos.Stdout, args, true); err != nil {
		if blocked, ok := nomivmhost.IsBlocked(err); ok {
			blocked.Write(stdos.Stderr, nomivmhost.DisplayPath(entryPath))
		} else {
			nomivmhost.WriteFailure(stdos.Stderr, err)
		}
		stdos.Exit(1)
	}
}

// buildImageVM is nomi build's half of the wrapper: lower the entry with the
// project's bindings and write its IR image to args[0], or report what
// nomi run would report and write nothing.
func buildImageVM(entryPath string, args []string) {
	if len(args) < 1 {
		stdfmt.Fprintln(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode vmimage <entry.nomi> <image>")
		stdos.Exit(1)
	}
	p, err := nomivmhost.Load(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath)))
	if err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
	image, usesCompiler, err := p.BuildImage()
	if err != nil {
		if blocked, ok := nomivmhost.IsBlocked(err); ok {
			blocked.Write(stdos.Stderr, nomivmhost.DisplayPath(entryPath))
		} else {
			stdfmt.Fprintln(stdos.Stderr, err)
		}
		stdos.Exit(1)
	}
	if err := stdos.WriteFile(args[0], image, 0o644); err != nil {
		stdfmt.Fprintln(stdos.Stderr, err)
		stdos.Exit(1)
	}
	if usesCompiler {
		stdfmt.Println(imageUsesCompilerMarker)
	}
}

func runTestFileVM(testPath string, args []string, format nomivmhost.TestFormat) {
	opts := nomivmhost.TestOptions{}
	if len(args) > 0 && args[0] != "" {
		line, err := stdstrconv.Atoi(args[0])
		if err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi test: invalid line %q\n", args[0])
			stdfmt.Printf("%s %d %d %d\n", ffiTestResultMarker, 0, 1, 0)
			stdos.Exit(1)
		}
		opts.Line = line
		opts.LineSet = true
	}
	rep := nomivmhost.NewTestReportFormat(stdos.Stdout, format)
	// In json mode stdout carries only records, so a case's own output goes
	// to stderr.
	out := stdos.Stdout
	if format == nomivmhost.TestFormatJSON {
		out = stdos.Stderr
	}
	p, err := nomivmhost.Load(testPath, nomivmhost.WithHosts(nomiHostTable(testPath)))
	if err != nil {
		rep.FailFile(testPath, err)
	} else {
		p.Test(out, rep, testPath, opts, func(name string) string { return nomivmhost.TestName(testPath, name) })
	}
	passed, failed := rep.Counts()
	blocked := rep.BlockedCount()
	stdfmt.Printf("%s %d %d %d\n", ffiTestResultMarker, passed, failed, blocked)
	if failed > 0 || blocked > 0 {
		stdos.Exit(1)
	}
}

var (
	_ = errors.New
	_ = fmt.Errorf
)

// nomiHostBound holds the descriptors the adapters build with, resolved once.
type nomiHostBound struct {
	env *hostadapt.Env
}

// nomiHostSpecs lists the descriptor specs the adapters build with, so an engine can
// link its own descriptors for them before nomiHostBind.
func nomiHostSpecs() []*hostadapt.DescSpec {
	return []*hostadapt.DescSpec{}
}

// nomiHostNames lists every binding this file adapts, in table order.
func nomiHostNames() []string {
	return []string{}
}

// nomiHostBind resolves every descriptor through env and answers the adapters by
// binding name.
func nomiHostBind(env *hostadapt.Env) (map[string]hostadapt.Func, error) {
	b := &nomiHostBound{env: env}
	_ = b
	return map[string]hostadapt.Func{}, nil
}

// nomiHostTable is the VM host table of this wrapper's bindings: the
// generated adapters, each keyed as the program at targetPath crosses under
// it.
func nomiHostTable(targetPath string) func(*hostadapt.Env) (map[string]hostadapt.Func, error) {
	return func(env *hostadapt.Env) (map[string]hostadapt.Func, error) {
		funcs, err := nomiHostBind(env)
		if err != nil {
			return nil, err
		}
		funcs["sqlite.open_raw"] = func(*rt.Frame, []rt.Value) (rt.Value, error) {
			return nil, errors.New("the FFI wrapper generated no VM host adapter for sqlite.open_raw: module sqlite: no source")
		}
		return funcs, nil
	}
}
