; GENERATED by scripts/sync-nvim-runtime.sh from editors/helix/runtime/queries/nomi/locals.scm.
; Do not edit; change the source and run `make build-nvim`.

;; Scopes

(source_file) @local.scope
(body) @local.scope
(function_definition) @local.scope
(lambda) @local.scope
(test_declaration) @local.scope
(tests_declaration) @local.scope

;; Definitions

(parameter
  name: (identifier) @local.definition.parameter)

(lambda_parameter
  name: (identifier) @local.definition.parameter)

(lambda_parameter
  (identifier) @local.definition.parameter)

(binding
  . (identifier) @local.definition.var)

(destructuring_binding
  binding: (identifier) @local.definition.var)

(function_definition
  name: (identifier) @local.definition.function)

(import_selector_path
  (identifier) @local.definition.function)

(import_selector_path
  (type_identifier) @local.definition.type)

(import_entry
  (identifier) @local.definition.function)

(import_entry
  (type_identifier) @local.definition.type)

(type_definition
  name: (qualified_type_identifier
    (type_identifier) @local.definition.type))

(type_alias
  name: (qualified_type_identifier
    (type_identifier) @local.definition.type))

(struct_definition
  name: (qualified_type_identifier
    (type_identifier) @local.definition.type))

(enum_definition
  name: (qualified_type_identifier
    (type_identifier) @local.definition.type))

(interface_definition
  name: (type_identifier) @local.definition.type)

(extern_type_definition
  name: (qualified_type_identifier
    (type_identifier) @local.definition.type))

;; References

(identifier) @local.reference
(type_identifier) @local.reference
