; GENERATED by scripts/sync-nvim-runtime.sh from editors/helix/runtime/queries/nomi/textobjects.scm.
; Do not edit; change the source and run `make build-nvim`.

(function_definition
  (body)? @function.inner) @function.outer

(interface_method
  (body)? @function.inner) @function.outer

(lambda
  body: (_) @function.inner) @function.outer

(test_declaration
  (body)? @function.inner) @function.outer

(tests_declaration
  (tests_body)? @class.inner) @class.outer

(struct_definition
  (struct_body)? @class.inner) @class.outer

(enum_definition
  (enum_body)? @class.inner) @class.outer

(type_definition
  (type_body)? @class.inner) @class.outer

(interface_definition
  (interface_method)* @class.inner) @class.outer

(impl_block
  [
    (decorated_impl_item)
    (function_definition)
    (extern_func_definition)
    (once_binding)
  ]* @class.inner) @class.outer

(parameters
  ((parameter) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(type_parameters
  ((type_parameter) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(call_expression
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(struct_construction
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

; A struct update's entries are its spread and its fields, so the parameter motions walk
; `{..base, x: 9}` the same way it walks `Point{x: 1, y: 2}` above.
(struct_update
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(map_literal
  ((map_entry) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(list
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(vector
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(tuple_expression
  ((_) @parameter.inner . ","? @parameter.outer) @parameter.outer)

(enum_variant) @parameter.outer

(field_definition
  (_) @parameter.inner) @parameter.outer

[
  (line_comment)
  (doc_comment)
] @comment.inner

[
  (line_comment)
  (doc_comment)
]+ @comment.outer
