package hostgen

import (
	"bytes"
	"fmt"
	"go/format"
	"maps"
	"path"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/nomi-language/nomi/internal/ast"
	"github.com/nomi-language/nomi/rt"
)

// Binding is one adapter to generate: the table's name for it, the Go
// function value, and the Nomi declaration it implements.
type Binding struct {
	Key string
	// Fn is the Go function value, for a table whose functions are linked
	// into the generator (the stdlib). Go describes the function instead for
	// one read from source (a project's FFI bindings); exactly one is set.
	Fn   any
	Go   *GoFunc
	Decl HostFunc
	// PanicsPropagate leaves out the adapter's recover. See
	// FuncRow.PanicsPropagate.
	PanicsPropagate bool
}

// GoFunc is a Go function known by its declaration rather than by a linked
// value: its package's import path ("" for the generated file's own package),
// its name, and its type, whose Kind is reflect.Func.
type GoFunc struct {
	Pkg  string
	Name string
	Type Type
}

// Generator accumulates the adapters of one generated file.
type Generator struct {
	pkg     string
	res     *Resolver
	handles map[string]string // TypeKey -> qualified host type name

	imports map[string]string // import path -> alias
	taken   map[string]bool   // aliases in use

	methods  bytes.Buffer
	memo     map[string]string // conversion key -> method name
	next     int
	descs    []descField
	descMemo map[string]string
	entries  []entry

	// ownPkg is the import path of the package the file is generated into,
	// whose types and functions are spelled unqualified. Empty for a
	// package of its own.
	ownPkg string
	// prefix names the file's top-level declarations, so a fragment can be
	// emitted into a file that declares its own.
	prefix string
}

type descField struct {
	field string
	spec  string // Go expression for a *hostadapt.DescSpec, or "" for a tuple
	tuple string // Go expression for a tuple descriptor
}

type entry struct {
	key, method string
}

// New starts a generated file in package pkg. handles maps every registered
// host type's Go type (both T and *T) to its qualified Nomi name.
func New(pkg string, res *Resolver, handles map[string]string) *Generator {
	g := &Generator{
		pkg:      pkg,
		res:      res,
		handles:  handles,
		imports:  map[string]string{},
		taken:    map[string]bool{},
		memo:     map[string]string{},
		descMemo: map[string]string{},
	}
	for _, reserved := range []string{"rt", "hostadapt", "fmt", "errors", "b", "v", "r", "x", "err"} {
		g.taken[reserved] = true
	}
	g.imports["github.com/nomi-language/nomi/rt"] = "rt"
	g.imports["github.com/nomi-language/nomi/hostadapt"] = "hostadapt"
	g.imports["fmt"] = "fmt"
	g.imports["errors"] = "errors"
	return g
}

// Add generates the adapter for one binding.
//
// A refused binding leaves the generator as it found it, so a caller that
// skips refusals (internal/ffirun, which turns each into an adapter answering
// the refusal) can go on adding: a conversion method is memoized before its
// body is written, and one a refusal abandoned half-written must not be
// reused by a later binding.
func (g *Generator) Add(b Binding) error {
	restore := g.snapshot()
	method, err := g.adapter(b)
	if err != nil {
		restore()
		return fmt.Errorf("%s: %w", b.Key, err)
	}
	g.entries = append(g.entries, entry{key: b.Key, method: method})
	return nil
}

// snapshot answers a function restoring every piece of state an adapter
// adds to.
func (g *Generator) snapshot() func() {
	methods := g.methods.Len()
	next := g.next
	descs := len(g.descs)
	memo := maps.Clone(g.memo)
	descMemo := maps.Clone(g.descMemo)
	imports := maps.Clone(g.imports)
	taken := maps.Clone(g.taken)
	return func() {
		g.methods.Truncate(methods)
		g.next = next
		g.descs = g.descs[:descs]
		g.memo, g.descMemo, g.imports, g.taken = memo, descMemo, imports, taken
	}
}

// Source renders the file.
func (g *Generator) Source(header string) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by internal/hostgen; DO NOT EDIT.\n%s\npackage %s\n\n", header, g.pkg)
	paths := make([]string, 0, len(g.imports))
	for p := range g.imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	out.WriteString("import (\n")
	for _, p := range paths {
		if g.imports[p] == path.Base(p) {
			fmt.Fprintf(&out, "\t%q\n", p)
		} else {
			fmt.Fprintf(&out, "\t%s %q\n", g.imports[p], p)
		}
	}
	out.WriteString(")\n\n")
	out.Write(g.decls())
	src, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("formatting generated source: %w", err)
	}
	return src, nil
}

// Fragment renders the file's declarations without a package clause or an
// import block, for a file that has its own, and answers the imports they
// need by path. A fragment's top-level names carry the generator's prefix
// (SetPrefix): Bind is `<prefix>Bind`, and so on.
func (g *Generator) Fragment() ([]byte, map[string]string) {
	imports := make(map[string]string, len(g.imports))
	for p, a := range g.imports {
		imports[p] = a
	}
	return g.decls(), imports
}

// SetPrefix names the generated top-level declarations with prefix, so they
// can share a package with other code.
func (g *Generator) SetPrefix(prefix string) { g.prefix = prefix }

// SetOwnPackage makes the generator spell types and functions of the package
// at importPath unqualified: the package the output is compiled into.
func (g *Generator) SetOwnPackage(importPath string) { g.ownPkg = importPath }

// UseImport makes the generator refer to the package at importPath by alias,
// and reserves names the generated code must not take as an alias.
func (g *Generator) UseImport(importPath, alias string) {
	g.imports[importPath] = alias
	g.taken[alias] = true
}

// Reserve keeps names the generated code must not take as import aliases.
func (g *Generator) Reserve(names ...string) {
	for _, n := range names {
		g.taken[n] = true
	}
}

// ident is a generated top-level name. Unprefixed, it is the stdlib files'
// spelling (bound, Specs, Names, Bind, spec_d0).
func (g *Generator) ident(name string) string {
	if g.prefix == "" {
		return name
	}
	return g.prefix + strings.ToUpper(name[:1]) + name[1:]
}

func (g *Generator) decls() []byte {
	var out bytes.Buffer
	bound, spec := g.ident("bound"), g.ident("spec_")
	if g.prefix == "" {
		spec = "spec_"
	}
	fmt.Fprintf(&out, "var (\n\t_ = %s.New\n\t_ = %s.Errorf\n)\n\n", g.imports["errors"], g.imports["fmt"])

	for _, d := range g.descs {
		if d.spec != "" {
			fmt.Fprintf(&out, "var %s%s = %s\n\n", spec, d.field, d.spec)
		}
	}
	fmt.Fprintf(&out, "// %s holds the descriptors the adapters build with, resolved once.\ntype %s struct {\n\tenv *hostadapt.Env\n", bound, bound)
	for _, d := range g.descs {
		fmt.Fprintf(&out, "\t%s *rt.TypeDesc\n", d.field)
	}
	out.WriteString("}\n\n")

	fmt.Fprintf(&out, "// %s lists the descriptor specs the adapters build with, so an engine can\n// link its own descriptors for them before %s.\nfunc %s() []*hostadapt.DescSpec {\n\treturn []*hostadapt.DescSpec{\n", g.ident("Specs"), g.ident("Bind"), g.ident("Specs"))
	for _, d := range g.descs {
		if d.spec != "" {
			fmt.Fprintf(&out, "\t\t%s%s,\n", spec, d.field)
		}
	}
	out.WriteString("\t}\n}\n\n")

	fmt.Fprintf(&out, "// %s lists every binding this file adapts, in table order.\nfunc %s() []string {\n\treturn []string{\n", g.ident("Names"), g.ident("Names"))
	for _, e := range g.entries {
		fmt.Fprintf(&out, "\t\t%q,\n", e.key)
	}
	out.WriteString("\t}\n}\n\n")

	fmt.Fprintf(&out, "// %s resolves every descriptor through env and answers the adapters by\n// binding name.\nfunc %s(env *hostadapt.Env) (map[string]hostadapt.Func, error) {\n\tb := &%s{env: env}\n", g.ident("Bind"), g.ident("Bind"), bound)
	if len(g.descs) > 0 {
		out.WriteString("\tvar err error\n")
	}
	for _, d := range g.descs {
		if d.spec != "" {
			fmt.Fprintf(&out, "\tif b.%s, err = env.Desc(%s%s); err != nil {\n\t\treturn nil, err\n\t}\n", d.field, spec, d.field)
		} else {
			fmt.Fprintf(&out, "\tb.%s = %s\n", d.field, d.tuple)
		}
	}
	if len(g.entries) == 0 {
		out.WriteString("\t_ = b\n")
	}
	out.WriteString("\treturn map[string]hostadapt.Func{\n")
	for _, e := range g.entries {
		fmt.Fprintf(&out, "\t\t%q: b.%s,\n", e.key, e.method)
	}
	out.WriteString("\t}, nil\n}\n\n")
	methods := g.methods.String()
	if bound != "bound" {
		methods = strings.ReplaceAll(methods, "(b *bound)", "(b *"+bound+")")
	}
	out.WriteString(methods)
	return out.Bytes()
}

// --- the adapter -------------------------------------------------------------

func (g *Generator) adapter(b Binding) (string, error) {
	var ft Type
	var call string
	if b.Go != nil {
		ft = b.Go.Type
		if ft == nil || ft.Kind() != reflect.Func {
			return "", fmt.Errorf("the binding's Go type is not a function")
		}
		call = b.Go.Name
		if b.Go.Pkg != "" && b.Go.Pkg != g.ownPkg {
			call = g.alias(b.Go.Pkg) + "." + b.Go.Name
		}
	} else {
		fv := reflect.ValueOf(b.Fn)
		if !fv.IsValid() || fv.Kind() != reflect.Func {
			return "", fmt.Errorf("the binding is not a function value")
		}
		ft = ReflectType(fv.Type())
		var err error
		if call, err = g.funcName(fv); err != nil {
			return "", err
		}
	}
	if ft.IsVariadic() {
		return "", fmt.Errorf("a variadic Go function has no Nomi projection")
	}
	decl := b.Decl.Decl
	// A Go function whose first parameter is *rt.Frame is handed the
	// caller's frame: it is a cancellation point or reads the activation,
	// which is read off the signature rather than declared, as irbuild's
	// hostFn.takesFrame is.
	takesFrame := ft.NumIn() > 0 && isFrame(ft.In(0))
	first := 0
	if takesFrame {
		first = 1
	}
	if len(decl.Params) != ft.NumIn()-first {
		return "", fmt.Errorf("the declaration takes %d parameter(s) and %s takes %d", len(decl.Params), call, ft.NumIn()-first)
	}
	want, err := g.res.Shape(b.Decl.Module, decl.ReturnTypeExpr)
	if err != nil {
		return "", fmt.Errorf("result: %w", err)
	}
	numOut := ft.NumOut()
	hasErr := numOut > 0 && isErrorType(ft.Out(numOut-1))
	numVals := numOut
	if hasErr {
		numVals--
	}
	for i := range numVals {
		if isErrorType(ft.Out(i)) {
			return "", fmt.Errorf("Go result %d is error; error is only supported as the final result", i)
		}
	}

	name := g.fresh("fn")
	var w bytes.Buffer
	key := strconv.Quote(b.Key)
	fmt.Fprintf(&w, "// %s adapts %s: %s(%s): %s\n", name, b.Key, decl.Name, paramList(decl), want)
	fmt.Fprintf(&w, "func (b *bound) %s(fr *rt.Frame, args []rt.Value) (_ rt.Value, err error) {\n", name)
	if !b.PanicsPropagate {
		fmt.Fprintf(&w, "\tdefer hostadapt.Recover(%s, &err)\n", key)
	}
	n := len(decl.Params)
	fmt.Fprintf(&w, "\tif len(args) != %d {\n\t\treturn nil, hostadapt.Arity(%s, %d, len(args))\n\t}\n", n, key, n)
	var argNames []string
	if takesFrame {
		argNames = append(argNames, "fr")
	}
	for i := range n {
		ps, err := g.res.Shape(b.Decl.Module, decl.Params[i].TypeAnnotation)
		if err != nil {
			return "", fmt.Errorf("parameter %s: %w", decl.Params[i].Name, err)
		}
		conv, err := g.in(ps, ft.In(first+i))
		if err != nil {
			return "", fmt.Errorf("parameter %s (%s) to Go %s: %w", decl.Params[i].Name, ps, ft.In(first+i), err)
		}
		argNames = append(argNames, fmt.Sprintf("a%d", i))
		fmt.Fprintf(&w, "\ta%d, err := b.%s(fr, args[%d])\n\tif err != nil {\n\t\treturn nil, hostadapt.Arg(%s, %d, err)\n\t}\n", i, conv, i, key, i)
	}
	results := make([]string, numOut)
	for i := range numVals {
		results[i] = fmt.Sprintf("r%d", i)
	}
	if hasErr {
		results[numOut-1] = "e"
	}
	if numOut == 0 {
		fmt.Fprintf(&w, "\t%s(%s)\n", call, strings.Join(argNames, ", "))
	} else {
		fmt.Fprintf(&w, "\t%s := %s(%s)\n", strings.Join(results, ", "), call, strings.Join(argNames, ", "))
	}

	payload := want
	if hasErr {
		if want.Kind != SResult || want.Elems[1].Kind != SString {
			return "", fmt.Errorf("%s returns a trailing error, so the declaration must return Result<_, String>, not %s", call, want)
		}
		payload = want.Elems[0]
		res := g.enumDesc(want)
		fmt.Fprintf(&w, "\tif e != nil {\n\t\trec := b.%s.NewVariant(1)\n\t\trec.S[0] = e.Error()\n\t\treturn rec, nil\n\t}\n", res)
	}
	vals := make([]Type, numVals)
	for i := range numVals {
		vals[i] = ft.Out(i)
	}
	value, err := g.results(&w, key, payload, vals)
	if err != nil {
		return "", err
	}
	if hasErr {
		res := g.enumDesc(want)
		fmt.Fprintf(&w, "\tok := b.%s.NewVariant(0)\n", res)
		if err := g.store(&w, "ok", 0, payload, nil, value, true, ""); err != nil {
			return "", err
		}
		value = "ok"
	}
	fmt.Fprintf(&w, "\treturn %s, nil\n}\n\n", value)
	g.methods.Write(w.Bytes())
	return name, nil
}

// results converts the value-carrying Go results r0..rN-1 into one rt.Value
// of shape want, and answers the expression holding it: Unit for none, the
// value for one, a tuple for more.
func (g *Generator) results(w *bytes.Buffer, key string, want *Shape, vals []Type) (string, error) {
	switch len(vals) {
	case 0:
		if want.Kind != SUnit {
			return "", fmt.Errorf("the Go function returns no value and the declaration returns %s", want)
		}
		return "rt.Unit{}", nil
	case 1:
		conv, err := g.out(want, vals[0])
		if err != nil {
			return "", fmt.Errorf("result %s from Go %s: %w", want, vals[0], err)
		}
		fmt.Fprintf(w, "\tv0, err := b.%s(r0)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n", conv)
		return "v0", nil
	}
	if want.Kind != STuple || len(want.Elems) != len(vals) {
		return "", fmt.Errorf("the Go function returns %d values, which project to a %d-tuple, and the declaration returns %s", len(vals), len(vals), want)
	}
	slots := make([]rt.SlotType, len(vals))
	for i, e := range want.Elems {
		slots[i] = e.Slot()
	}
	d := g.tupleDesc(slots)
	fmt.Fprintf(w, "\ttup := b.%s.New()\n", d)
	offsets := layoutOffsets(slots)
	for i, e := range want.Elems {
		if err := g.store(w, "tup", offsets[i], e, vals[i], fmt.Sprintf("r%d", i), false, fmt.Sprintf("fmt.Errorf(\"%%s: marshaling return %d: %%v\", %s, err)", i, key)); err != nil {
			return "", fmt.Errorf("tuple item %d: %w", i, err)
		}
	}
	return "tup", nil
}

// store writes a value into slot off of record rec. When boxed is set, expr
// is already an rt.Value of shape s; otherwise it is a Go value of type t,
// converted here. wrap, when set, is the Go expression a conversion failure
// held in `err` is returned as, so the text matches the marshaller's at the
// same position; empty returns err itself.
func (g *Generator) store(w *bytes.Buffer, rec string, off int, s *Shape, t Type, expr string, boxed bool, wrap string) error {
	if wrap == "" {
		wrap = "err"
	}
	if boxed {
		switch s.Kind {
		case SInt:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.IntWord(%s.(int64))\n", rec, off, expr)
		case SFloat:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.FloatWord(%s.(float64))\n", rec, off, expr)
		case SBool:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.BoolWord(%s.(bool))\n", rec, off, expr)
		case SByte:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.ByteWord(%s.(rt.Byte))\n", rec, off, expr)
		case SString:
			fmt.Fprintf(w, "\t%s.S[%d] = %s.(string)\n", rec, off, expr)
		case SBytes:
			fmt.Fprintf(w, "\t%s.S[%d] = string(%s.(rt.Bytes))\n", rec, off, expr)
		default:
			fmt.Fprintf(w, "\t%s.R[%d] = %s\n", rec, off, expr)
		}
		return nil
	}
	if isScalar(s) {
		x, fallible, err := g.widen(s, t, expr)
		if err != nil {
			return err
		}
		if fallible {
			v := g.fresh("w")
			fmt.Fprintf(w, "\t%s, err := %s\n\tif err != nil {\n\t\treturn nil, %s\n\t}\n", v, x, wrap)
			x = v
		}
		switch s.Kind {
		case SInt:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.IntWord(%s)\n", rec, off, x)
		case SFloat:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.FloatWord(%s)\n", rec, off, x)
		case SBool:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.BoolWord(%s)\n", rec, off, x)
		case SByte:
			fmt.Fprintf(w, "\t%s.W[%d] = rt.ByteWord(%s)\n", rec, off, x)
		case SString:
			fmt.Fprintf(w, "\t%s.S[%d] = %s\n", rec, off, x)
		case SBytes:
			fmt.Fprintf(w, "\t%s.S[%d] = string(%s)\n", rec, off, x)
		}
		return nil
	}
	conv, err := g.out(s, t)
	if err != nil {
		return err
	}
	v := g.fresh("w")
	fmt.Fprintf(w, "\t%s, err := b.%s(%s)\n\tif err != nil {\n\t\treturn nil, %s\n\t}\n\t%s.R[%d] = %s\n", v, conv, expr, wrap, rec, off, v)
	return nil
}

// --- Nomi value -> Go value --------------------------------------------------

// in answers the name of a method `func (b *bound) NAME(v rt.Value) (T, error)`.
func (g *Generator) in(s *Shape, t Type) (string, error) {
	key := "in|" + shapeKey(s) + "|" + t.String() + "|" + t.PkgPath()
	if m, ok := g.memo[key]; ok {
		return m, nil
	}
	goT, err := g.typ(t)
	if err != nil {
		return "", err
	}
	name := g.fresh("in")
	g.memo[key] = name
	var w bytes.Buffer
	fmt.Fprintf(&w, "// %s reads a %s as Go %s.\nfunc (b *bound) %s(fr *rt.Frame, v rt.Value) (out %s, err error) {\n", name, s, goT, name, goT)
	fail := "\t\treturn out, err\n"
	switch {
	case isScalar(s):
		if err := compatible(s, t); err != nil {
			return "", err
		}
		nomiT := nomiGoType(s)
		fmt.Fprintf(&w, "\tx, ok := v.(%s)\n\tif !ok {\n\t\treturn out, hostadapt.Want(%q, v)\n\t}\n", nomiT, s.String())
		x, fallible, err := g.narrow(s, t, "x")
		if err != nil {
			return "", err
		}
		if fallible {
			fmt.Fprintf(&w, "\treturn %s\n", x)
		} else {
			fmt.Fprintf(&w, "\treturn %s, nil\n", x)
		}
	case s.Kind == SList && t.Kind() == reflect.Slice && !isByteKind(t.Elem()):
		elem, err := g.in(s.Elems[0], t.Elem())
		if err != nil {
			return "", fmt.Errorf("element: %w", err)
		}
		fmt.Fprintf(&w, "\txs, err := hostadapt.List(v)\n\tif err != nil {\n%s\t}\n", fail)
		fmt.Fprintf(&w, "\tout = make(%s, 0, hostadapt.Len(xs))\n\ti := 0\n", goT)
		fmt.Fprintf(&w, "\tfor c := xs; c != nil; c = c.Tail {\n\t\te, err := b.%s(fr, c.Head)\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"index %%d: %%w\", i, err)\n\t\t}\n\t\tout = append(out, e)\n\t\ti++\n\t}\n\treturn out, nil\n", elem)
	case isRtGeneric(t, "Maybe", "Result", "List", "Map"):
		if err := g.inRtGeneric(&w, s, t, goT); err != nil {
			return "", err
		}
	case s.Kind == SMap && t.Kind() == reflect.Map && g.handles[TypeKey(t)] == "":
		kin, err := g.in(s.Elems[0], t.Key())
		if err != nil {
			return "", fmt.Errorf("key: %w", err)
		}
		vin, err := g.in(s.Elems[1], t.Elem())
		if err != nil {
			return "", fmt.Errorf("value: %w", err)
		}
		fmt.Fprintf(&w, "\tm, ok := v.(rt.Map[any, any])\n\tif !ok {\n\t\treturn out, hostadapt.Want(%q, v)\n\t}\n", s.String())
		fmt.Fprintf(&w, "\tents := rt.MapEntries(m)\n\tout = make(%s, len(ents))\n\tfor i, e := range ents {\n", goT)
		fmt.Fprintf(&w, "\t\tk, err := b.%s(fr, e.Key)\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"key %%d: %%w\", i, err)\n\t\t}\n", kin)
		fmt.Fprintf(&w, "\t\tx, err := b.%s(fr, e.Val)\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"value %%d: %%w\", i, err)\n\t\t}\n", vin)
		w.WriteString("\t\tout[k] = x\n\t}\n\treturn out, nil\n")
	case s.Kind == SMap:
		return "", fmt.Errorf("Go %s: the adapter generator does not convert this type yet; a Map crosses as rt.Map[K, V] or a Go map", t)
	case s.Kind == SEnum:
		if err := g.inEnum(&w, s, t); err != nil {
			return "", err
		}
	case s.Kind == SHost && g.handles[TypeKey(t)] == "" && rtHeld[s.Name] != "":
		if rtHeld[s.Name] != TypeKey(t) {
			return "", fmt.Errorf("%s crosses as Go %s, not %s", s.Name, rtHeld[s.Name], t)
		}
		fmt.Fprintf(&w, "\tx, ok := v.(%s)\n\tif !ok {\n\t\treturn out, hostadapt.Want(%q, v)\n\t}\n\treturn x, nil\n", goT, s.String())
	case s.Kind == SMaybe && t.Kind() == reflect.Pointer && g.handles[TypeKey(t)] == "":
		elem, err := g.in(s.Elems[0], t.Elem())
		if err != nil {
			return "", fmt.Errorf("Maybe payload: %w", err)
		}
		fmt.Fprintf(&w, "\tr, tag, err := hostadapt.Variant(v, %q)\n\tif err != nil {\n%s\t}\n", maybeName, fail)
		fmt.Fprintf(&w, "\tswitch tag {\n\tcase \"None\":\n\t\treturn nil, nil\n\tcase \"Some\":\n\t\tx, err := b.%s(fr, hostadapt.Payload(r))\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"Some: %%w\", err)\n\t\t}\n\t\treturn &x, nil\n\t}\n", elem)
		fmt.Fprintf(&w, "\treturn nil, fmt.Errorf(\"unmarshal Maybe: unknown variant %%q\", tag)\n")
	case s.Kind == SStruct && t.Kind() == reflect.Struct && g.handles[TypeKey(t)] == "":
		fields, err := goFields(t)
		if err != nil {
			return "", err
		}
		if err := sameFields(s, fields); err != nil {
			return "", err
		}
		d := g.structDesc(s)
		fmt.Fprintf(&w, "\tr, err := hostadapt.Record(v, %q)\n\tif err != nil {\n%s\t}\n", s.Name, fail)
		offsets := layoutOffsets(fieldSlots(s))
		for i, f := range s.Fields {
			gf := fields[f.Name]
			if err := g.readField(&w, d, i, offsets[i], f, gf); err != nil {
				return "", fmt.Errorf("field %s: %w", f.Name, err)
			}
		}
		w.WriteString("\treturn out, nil\n")
	case s.Kind == SDistinct && len(s.Elems) == 1 && isScalar(s.Elems[0]):
		inner := s.Elems[0]
		d := g.distinctDesc(s)
		fmt.Fprintf(&w, "\tr, err := hostadapt.Record(v, %q)\n\tif err != nil {\n%s\t}\n", s.Name, fail)
		switch {
		case isTimeDuration(t):
			if s.Name != durationName {
				return "", fmt.Errorf("Go time.Duration projects to Duration, not %s", s)
			}
			fmt.Fprintf(&w, "\tx, err := hostadapt.IntField(r, b.%s, 0, 0, \"\")\n\tif err != nil {\n%s\t}\n\treturn %s(x), nil\n", d, fail, goT)
		case isTimeTime(t):
			if s.Name != instantName {
				return "", fmt.Errorf("Go time.Time projects to Instant, not %s", s)
			}
			g.imports["time"] = "time"
			fmt.Fprintf(&w, "\tx, err := hostadapt.IntField(r, b.%s, 0, 0, \"\")\n\tif err != nil {\n%s\t}\n\treturn time.Unix(0, x).UTC(), nil\n", d, fail)
		default:
			if err := compatible(inner, t); err != nil {
				return "", fmt.Errorf("%s over %s: %w", s, inner, err)
			}
			fmt.Fprintf(&w, "\tx, err := hostadapt.%s(r, b.%s, 0, 0, \"\")\n\tif err != nil {\n%s\t}\n", fieldReader(inner), d, fail)
			x, fallible, err := g.narrow(inner, t, "x")
			if err != nil {
				return "", err
			}
			if fallible {
				fmt.Fprintf(&w, "\treturn %s\n", x)
			} else {
				fmt.Fprintf(&w, "\treturn %s, nil\n", x)
			}
		}
	case s.Kind == SHost:
		if got := g.handles[TypeKey(t)]; got != s.Name {
			return "", fmt.Errorf("Go %s is not registered as host type %s (registered: %q)", t, s.Name, got)
		}
		fmt.Fprintf(&w, "\th, err := hostadapt.Handle(v, %q)\n\tif err != nil {\n%s\t}\n", s.Name, fail)
		fmt.Fprintf(&w, "\tp, ok := h.(%s)\n\tif !ok {\n\t\treturn out, fmt.Errorf(\"%s handle holds %%T, not %s\", h)\n\t}\n\treturn p, nil\n", goT, s.Name, goT)
	case s.Kind == SFunc && t.Kind() == reflect.Func:
		if err := g.callback(&w, s, t, goT); err != nil {
			return "", fmt.Errorf("callback: %w", err)
		}
	default:
		return "", fmt.Errorf("no conversion from %s to Go %s", s, t)
	}
	w.WriteString("}\n\n")
	g.methods.Write(w.Bytes())
	return name, nil
}

// readField reads struct field i of r into out's Go field.
func (g *Generator) readField(w *bytes.Buffer, d string, i, off int, f ShapeField, gf goField) error {
	target := "out." + gf.path
	if isScalar(f.Shape) {
		if err := compatible(f.Shape, gf.typ); err != nil {
			return err
		}
		fmt.Fprintf(w, "\t{\n\t\tx, err := hostadapt.%s(r, b.%s, %d, %d, %q)\n\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n", fieldReader(f.Shape), d, i, off, f.Name)
		x, fallible, err := g.narrow(f.Shape, gf.typ, "x")
		if err != nil {
			return err
		}
		if fallible {
			fmt.Fprintf(w, "\t\ty, err := %s\n\t\tif err != nil {\n\t\t\treturn out, fmt.Errorf(\"field %%q: %%w\", %q, err)\n\t\t}\n\t\t%s = y\n\t}\n", x, f.Name, target)
		} else {
			fmt.Fprintf(w, "\t\t%s = %s\n\t}\n", target, x)
		}
		return nil
	}
	conv, err := g.in(f.Shape, gf.typ)
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "\t{\n\t\tx, err := hostadapt.RefField(r, b.%s, %d, %d, %q)\n\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n\t\ty, err := b.%s(fr, x)\n\t\tif err != nil {\n\t\t\treturn out, fmt.Errorf(\"field %%q: %%w\", %q, err)\n\t\t}\n\t\t%s = y\n\t}\n", d, i, off, f.Name, conv, f.Name, target)
	return nil
}

// callback writes the body of an `in` method that turns a Nomi function value
// into a Go func calling back through the Env, with the marshaller's rules for
// what a Go callback does with the result and with a failure.
func (g *Generator) callback(w *bytes.Buffer, s *Shape, t Type, goT string) error {
	if t.IsVariadic() {
		return fmt.Errorf("a variadic Go callback has no Nomi projection")
	}
	if t.NumIn() != len(s.Elems) {
		return fmt.Errorf("the Nomi function takes %d argument(s) and Go %s takes %d", len(s.Elems), t, t.NumIn())
	}
	numOut := t.NumOut()
	lastErr := numOut > 0 && isErrorType(t.Out(numOut-1))
	if numOut > 2 || (numOut == 2 && !lastErr) {
		return fmt.Errorf("a Go callback returns nothing, one value, or a value and an error; %s does not", t)
	}
	params := make([]string, t.NumIn())
	operands := make([]string, t.NumIn())
	var pre bytes.Buffer
	for i := range t.NumIn() {
		pt, err := g.typ(t.In(i))
		if err != nil {
			return err
		}
		params[i] = fmt.Sprintf("p%d %s", i, pt)
		if isScalar(s.Elems[i]) {
			x, fallible, err := g.widen(s.Elems[i], t.In(i), fmt.Sprintf("p%d", i))
			if err != nil {
				return fmt.Errorf("argument %d: %w", i, err)
			}
			if fallible {
				fmt.Fprintf(&pre, "\t\tx%d, err := %s\n\t\tif err != nil {\n\t\t\tpanic(fmt.Sprintf(\"Nomi callback arg %d: %%v\", err))\n\t\t}\n", i, x, i)
				operands[i] = fmt.Sprintf("x%d", i)
			} else {
				operands[i] = x
			}
			continue
		}
		conv, err := g.out(s.Elems[i], t.In(i))
		if err != nil {
			return fmt.Errorf("argument %d: %w", i, err)
		}
		fmt.Fprintf(&pre, "\t\tx%d, err := b.%s(p%d)\n\t\tif err != nil {\n\t\t\tpanic(fmt.Sprintf(\"Nomi callback arg %d: %%v\", err))\n\t\t}\n", i, conv, i, i)
		operands[i] = fmt.Sprintf("x%d", i)
	}
	outs := make([]string, numOut)
	zeros := make([]string, numOut)
	for i := range numOut {
		ot, err := g.typ(t.Out(i))
		if err != nil {
			return err
		}
		outs[i] = ot
		zeros[i] = fmt.Sprintf("z%d", i)
	}
	sig := strings.Join(outs, ", ")
	if numOut > 1 {
		sig = "(" + sig + ")"
	}
	// failWith is the callbackErrorReturns rule for an error held in errExpr.
	failWith := func(errExpr string) string {
		if !lastErr {
			return fmt.Sprintf("\t\t\tpanic(hostadapt.CallbackFailure(%s, %q))\n", errExpr, t.String())
		}
		var b strings.Builder
		for i := range numOut - 1 {
			fmt.Fprintf(&b, "\t\t\tvar z%d %s\n", i, outs[i])
		}
		ret := append(append([]string{}, zeros[:numOut-1]...), errExpr)
		fmt.Fprintf(&b, "\t\t\treturn %s\n", strings.Join(ret, ", "))
		return b.String()
	}

	fmt.Fprintf(w, "\tif v == nil {\n\t\treturn out, fmt.Errorf(\"expected a function, got nil\")\n\t}\n")
	fmt.Fprintf(w, "\treturn func(%s) %s {\n", strings.Join(params, ", "), sig)
	w.Write(pre.Bytes())
	fmt.Fprintf(w, "\t\tres, err := b.env.Call(fr, v, []rt.Value{%s})\n\t\tif err != nil {\n%s\t\t}\n", strings.Join(operands, ", "), failWith("err"))
	switch {
	case numOut == 0:
		w.WriteString("\t\t_ = res\n")
	case numOut == 1 && !lastErr:
		conv, err := g.in(s.Ret, t.Out(0))
		if err != nil {
			return fmt.Errorf("result: %w", err)
		}
		fmt.Fprintf(w, "\t\ty, err := b.%s(fr, res)\n\t\tif err != nil {\n%s\t\t}\n\t\treturn y\n", conv, failWith("err"))
	default:
		// The last Go result is an error, so the Nomi function returns a
		// Result whose Err carries a String.
		if s.Ret.Kind != SResult || s.Ret.Elems[1].Kind != SString {
			return fmt.Errorf("Go %s returns an error, so the Nomi function must return Result<_, String>, not %s", t, s.Ret)
		}
		fmt.Fprintf(w, "\t\tr, tag, err := hostadapt.Variant(res, %q)\n\t\tif err != nil {\n%s\t\t}\n", resultName, failWith("err"))
		fmt.Fprintf(w, "\t\tif tag == \"Err\" {\n\t\t\tmsg, ok := hostadapt.Payload(r).(string)\n\t\t\tif !ok {\n%s\t\t\t}\n%s\t\t}\n",
			indent(failWith("fmt.Errorf(\"unmarshal Result::Err: expected String payload, got %T\", hostadapt.Payload(r))")),
			indent(failWith("errors.New(msg)")))
		fmt.Fprintf(w, "\t\tif tag != \"Ok\" {\n%s\t\t}\n", indent(failWith("fmt.Errorf(\"unknown Result variant %q\", tag)")))
		if numOut == 1 {
			w.WriteString("\t\treturn nil\n")
		} else {
			conv, err := g.in(s.Ret.Elems[0], t.Out(0))
			if err != nil {
				return fmt.Errorf("result: %w", err)
			}
			fmt.Fprintf(w, "\t\ty, err := b.%s(fr, hostadapt.Payload(r))\n\t\tif err != nil {\n%s\t\t}\n\t\treturn y, nil\n", conv, failWith("err"))
		}
	}
	w.WriteString("\t}, nil\n")
	return nil
}

func indent(s string) string {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = "\t" + l
		}
	}
	return strings.Join(lines, "")
}

// --- Go value -> Nomi value --------------------------------------------------

// out answers the name of a method `func (b *bound) NAME(v T) (rt.Value, error)`.
func (g *Generator) out(s *Shape, t Type) (string, error) {
	key := "out|" + shapeKey(s) + "|" + t.String() + "|" + t.PkgPath()
	if m, ok := g.memo[key]; ok {
		return m, nil
	}
	goT, err := g.typ(t)
	if err != nil {
		return "", err
	}
	name := g.fresh("out")
	g.memo[key] = name
	var w bytes.Buffer
	fmt.Fprintf(&w, "// %s builds a %s from Go %s.\nfunc (b *bound) %s(v %s) (rt.Value, error) {\n", name, s, goT, name, goT)
	switch {
	case isScalar(s):
		x, fallible, err := g.widen(s, t, "v")
		if err != nil {
			return "", err
		}
		if fallible {
			fmt.Fprintf(&w, "\tx, err := %s\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn x, nil\n", x)
		} else {
			fmt.Fprintf(&w, "\treturn %s, nil\n", x)
		}
	case s.Kind == SUnit:
		w.WriteString("\treturn rt.Unit{}, nil\n")
	case isRtGeneric(t, "Maybe", "Result", "List", "Map"):
		if err := g.outRtGeneric(&w, s, t); err != nil {
			return "", err
		}
	case s.Kind == SMap && t.Kind() == reflect.Map && g.handles[TypeKey(t)] == "":
		// A Go map becomes an rt.Map[any, any] over the VM's own hash and
		// equality, as a Map literal's is; Go's iteration order does not
		// reach the Nomi value, whose order is the map's.
		kout, err := g.out(s.Elems[0], t.Key())
		if err != nil {
			return "", fmt.Errorf("key: %w", err)
		}
		vout, err := g.out(s.Elems[1], t.Elem())
		if err != nil {
			return "", fmt.Errorf("value: %w", err)
		}
		w.WriteString("\tconv := make([]rt.MapEntry[any, any], 0, len(v))\n\tfor gk, gv := range v {\n")
		fmt.Fprintf(&w, "\t\tk, err := b.%s(gk)\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"key %%v: %%w\", gk, err)\n\t\t}\n", kout)
		fmt.Fprintf(&w, "\t\tx, err := b.%s(gv)\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"value at %%v: %%w\", gk, err)\n\t\t}\n", vout)
		w.WriteString("\t\tconv = append(conv, rt.MapEntry[any, any]{Key: k, Val: x})\n\t}\n\treturn rt.MapOf(rt.Hash, rt.Equal, conv), nil\n")
	case s.Kind == SMap:
		return "", fmt.Errorf("Go %s: the adapter generator does not convert this type yet; a Map crosses as rt.Map[K, V] or a Go map", t)
	case s.Kind == SEnum:
		if err := g.outEnum(&w, s, t); err != nil {
			return "", err
		}
	case s.Kind == SHost && g.handles[TypeKey(t)] == "" && rtHeld[s.Name] != "":
		if rtHeld[s.Name] != TypeKey(t) {
			return "", fmt.Errorf("%s crosses as Go %s, not %s", s.Name, rtHeld[s.Name], t)
		}
		w.WriteString("\treturn v, nil\n")
	case s.Kind == SList && t.Kind() == reflect.Slice && !isByteKind(t.Elem()):
		elem, err := g.out(s.Elems[0], t.Elem())
		if err != nil {
			return "", fmt.Errorf("element: %w", err)
		}
		fmt.Fprintf(&w, "\tvar xs *rt.List[any]\n\tfor i := len(v) - 1; i >= 0; i-- {\n\t\tx, err := b.%s(v[i])\n\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"index %%d: %%w\", i, err)\n\t\t}\n\t\txs = rt.Cons[any](x, xs)\n\t}\n\treturn xs, nil\n", elem)
	case s.Kind == SMaybe && t.Kind() == reflect.Pointer && g.handles[TypeKey(t)] == "":
		d := g.enumDesc(s)
		fmt.Fprintf(&w, "\tif v == nil {\n\t\treturn b.%s.NewVariant(1), nil\n\t}\n\tr := b.%s.NewVariant(0)\n", d, d)
		if err := g.store(&w, "r", 0, s.Elems[0], t.Elem(), "*v", false, ""); err != nil {
			return "", fmt.Errorf("Maybe payload: %w", err)
		}
		w.WriteString("\treturn r, nil\n")
	case s.Kind == SStruct && t.Kind() == reflect.Struct && g.handles[TypeKey(t)] == "":
		fields, err := goFields(t)
		if err != nil {
			return "", err
		}
		if err := sameFields(s, fields); err != nil {
			return "", err
		}
		d := g.structDesc(s)
		fmt.Fprintf(&w, "\tr := b.%s.New()\n", d)
		offsets := layoutOffsets(fieldSlots(s))
		for i, f := range s.Fields {
			if err := g.store(&w, "r", offsets[i], f.Shape, fields[f.Name].typ, "v."+fields[f.Name].path, false, fmt.Sprintf("fmt.Errorf(\"field %%q: %%w\", %q, err)", f.Name)); err != nil {
				return "", fmt.Errorf("field %s: %w", f.Name, err)
			}
		}
		w.WriteString("\treturn r, nil\n")
	case s.Kind == SDistinct && len(s.Elems) == 1 && isScalar(s.Elems[0]):
		d := g.distinctDesc(s)
		fmt.Fprintf(&w, "\tr := b.%s.New()\n", d)
		switch {
		case isTimeDuration(t):
			if s.Name != durationName {
				return "", fmt.Errorf("Go time.Duration projects to Duration, not %s", s)
			}
			w.WriteString("\tr.W[0] = rt.IntWord(int64(v))\n")
		case isTimeTime(t):
			if s.Name != instantName {
				return "", fmt.Errorf("Go time.Time projects to Instant, not %s", s)
			}
			w.WriteString("\tn, err := hostadapt.InstantNanos(v)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tr.W[0] = rt.IntWord(n)\n")
		default:
			if err := g.store(&w, "r", 0, s.Elems[0], t, "v", false, ""); err != nil {
				return "", err
			}
		}
		w.WriteString("\treturn r, nil\n")
	case s.Kind == SHost:
		if got := g.handles[TypeKey(t)]; got != s.Name {
			return "", fmt.Errorf("Go %s is not registered as host type %s (registered: %q)", t, s.Name, got)
		}
		fmt.Fprintf(&w, "\treturn rt.HostHandle{TypeName: %q, Value: v}, nil\n", s.Name)
	default:
		return "", fmt.Errorf("no conversion from Go %s to %s", t, s)
	}
	w.WriteString("}\n\n")
	g.methods.Write(w.Bytes())
	return name, nil
}

// --- scalars -----------------------------------------------------------------

func isScalar(s *Shape) bool {
	switch s.Kind {
	case SInt, SFloat, SBool, SString, SByte, SBytes:
		return true
	}
	return false
}

// nomiGoType is the Go type an rt.Value of a scalar shape holds.
func nomiGoType(s *Shape) string {
	return map[ShapeKind]string{
		SInt: "int64", SFloat: "float64", SBool: "bool", SString: "string", SByte: "rt.Byte", SBytes: "rt.Bytes",
	}[s.Kind]
}

func fieldReader(s *Shape) string {
	return map[ShapeKind]string{
		SInt: "IntField", SFloat: "FloatField", SBool: "BoolField", SString: "StringField", SByte: "ByteField", SBytes: "BytesField",
	}[s.Kind]
}

func isByteKind(t Type) bool { return t.Kind() == reflect.Uint8 }

// compatible is the marshaller's projection table for scalars.
func compatible(s *Shape, t Type) error {
	if isTimeDuration(t) || isTimeTime(t) {
		return fmt.Errorf("Go %s projects to %s, not %s", t, map[bool]string{true: "Duration", false: "Instant"}[isTimeDuration(t)], s)
	}
	ok := false
	switch s.Kind {
	case SInt:
		switch t.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
			ok = true
		}
	case SFloat:
		ok = t.Kind() == reflect.Float32 || t.Kind() == reflect.Float64
	case SBool:
		ok = t.Kind() == reflect.Bool
	case SString:
		ok = t.Kind() == reflect.String
	case SByte:
		ok = t.Kind() == reflect.Uint8
	case SBytes:
		ok = isRtBytes(t) || (t.Kind() == reflect.Slice && isByteKind(t.Elem()))
	}
	if !ok {
		return fmt.Errorf("Go %s does not project to %s", t, s)
	}
	return nil
}

// narrow converts x, a Nomi scalar's Go value, to Go type t. A fallible
// conversion is an expression of two values, (T, error).
func (g *Generator) narrow(s *Shape, t Type, x string) (string, bool, error) {
	goT, err := g.typ(t)
	if err != nil {
		return "", false, err
	}
	switch s.Kind {
	case SInt:
		switch t.Kind() {
		case reflect.Int64:
			return fmt.Sprintf("%s(%s)", goT, x), false, nil
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32:
			return fmt.Sprintf("hostadapt.ToSigned[%s](%s, %q)", goT, x, t.String()), true, nil
		default:
			return fmt.Sprintf("hostadapt.ToUnsigned[%s](%s, %q)", goT, x, t.String()), true, nil
		}
	case SFloat:
		if t.Kind() == reflect.Float32 {
			return fmt.Sprintf("hostadapt.ToFloat32[%s](%s, %q)", goT, x, t.String()), true, nil
		}
		return fmt.Sprintf("%s(%s)", goT, x), false, nil
	case SBool, SString, SByte:
		return fmt.Sprintf("%s(%s)", goT, x), false, nil
	case SBytes:
		if isRtBytes(t) || isPredeclared(t.Elem(), "byte") {
			return fmt.Sprintf("%s(%s)", goT, x), false, nil
		}
		elemT, err := g.typ(t.Elem())
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("func() %s { out := make(%s, len(%s)); for i := range len(%s) { out[i] = %s(%s[i]) }; return out }()", goT, goT, x, x, elemT, x), false, nil
	}
	return "", false, fmt.Errorf("%s is not a scalar", s)
}

// widen converts x, a Go value of type t, to the Go value an rt.Value of
// scalar shape s holds.
func (g *Generator) widen(s *Shape, t Type, x string) (string, bool, error) {
	if err := compatible(s, t); err != nil {
		return "", false, err
	}
	switch s.Kind {
	case SInt:
		switch t.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return fmt.Sprintf("int64(%s)", x), false, nil
		}
		return fmt.Sprintf("hostadapt.FromUnsigned(%s, %q)", x, t.String()), true, nil
	case SFloat:
		return fmt.Sprintf("float64(%s)", x), false, nil
	case SBool:
		return fmt.Sprintf("bool(%s)", x), false, nil
	case SString:
		return fmt.Sprintf("string(%s)", x), false, nil
	case SByte:
		return fmt.Sprintf("rt.Byte(%s)", x), false, nil
	case SBytes:
		if isRtBytes(t) || isPredeclared(t.Elem(), "byte") {
			return fmt.Sprintf("rt.Bytes(%s)", x), false, nil
		}
		return fmt.Sprintf("func() rt.Bytes { out := make([]byte, len(%s)); for i := range len(%s) { out[i] = byte(%s[i]) }; return rt.Bytes(out) }()", x, x, x), false, nil
	}
	return "", false, fmt.Errorf("%s is not a scalar", s)
}

// --- descriptors -------------------------------------------------------------

func (g *Generator) addDesc(key, spec, tuple string) string {
	if f, ok := g.descMemo[key]; ok {
		return f
	}
	f := fmt.Sprintf("d%d", len(g.descs))
	g.descMemo[key] = f
	g.descs = append(g.descs, descField{field: f, spec: spec, tuple: tuple})
	return f
}

func (g *Generator) structDesc(s *Shape) string {
	var b strings.Builder
	fmt.Fprintf(&b, "&hostadapt.DescSpec{Name: %q, Kind: rt.KindStruct, Fields: []rt.FieldSpec{", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(&b, "{Name: %q, Type: %s}, ", f.Name, slotExpr(f.Shape.Slot()))
	}
	b.WriteString("}}")
	return g.addDesc("struct|"+shapeKey(s), b.String(), "")
}

func (g *Generator) distinctDesc(s *Shape) string {
	inner := "nil"
	if len(s.Elems) == 1 {
		inner = fmt.Sprintf("hostadapt.Slot(%s)", slotExpr(s.Elems[0].Slot()))
	}
	spec := fmt.Sprintf("&hostadapt.DescSpec{Name: %q, Kind: rt.KindDistinct, Inner: %s}", s.Name, inner)
	return g.addDesc("distinct|"+shapeKey(s), spec, "")
}

// enumDesc is the descriptor of a Maybe or Result instantiation. Tags follow
// the declarations: `Some` 0 and `None` 1, `Ok` 0 and `Err` 1.
func (g *Generator) enumDesc(s *Shape) string {
	var spec string
	switch s.Kind {
	case SMaybe:
		spec = fmt.Sprintf("&hostadapt.DescSpec{Name: %q, Kind: rt.KindEnum, Variants: []rt.VariantSpec{"+
			"{Name: \"Some\", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: %s}}}, "+
			"{Name: \"None\", Shape: rt.VariantBare}}}", maybeName, slotExpr(s.Elems[0].Slot()))
	case SResult:
		spec = fmt.Sprintf("&hostadapt.DescSpec{Name: %q, Kind: rt.KindEnum, Variants: []rt.VariantSpec{"+
			"{Name: \"Ok\", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: %s}}}, "+
			"{Name: \"Err\", Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: %s}}}}}",
			resultName, slotExpr(s.Elems[0].Slot()), slotExpr(s.Elems[1].Slot()))
	case SEnum:
		var b strings.Builder
		fmt.Fprintf(&b, "&hostadapt.DescSpec{Name: %q, Kind: rt.KindEnum, Variants: []rt.VariantSpec{", s.Name)
		for _, v := range s.Variants {
			switch {
			case v.Shape == rt.VariantBare:
				fmt.Fprintf(&b, "{Name: %q, Shape: rt.VariantBare}, ", v.Name)
			case v.Err != nil:
				// An unresolvable positional payload is still one payload,
				// held by reference.
				fmt.Fprintf(&b, "{Name: %q, Shape: rt.VariantPositional, Fields: []rt.FieldSpec{{Type: rt.SlotRef}}}, ", v.Name)
			default:
				shape := "rt.VariantPositional"
				if v.Shape == rt.VariantFields {
					shape = "rt.VariantFields"
				}
				fmt.Fprintf(&b, "{Name: %q, Shape: %s, Fields: []rt.FieldSpec{", v.Name, shape)
				for _, f := range v.Fields {
					if f.Name == "" {
						fmt.Fprintf(&b, "{Type: %s}, ", slotExpr(f.Shape.Slot()))
					} else {
						fmt.Fprintf(&b, "{Name: %q, Type: %s}, ", f.Name, slotExpr(f.Shape.Slot()))
					}
				}
				b.WriteString("}}, ")
			}
		}
		b.WriteString("}}")
		spec = b.String()
	default:
		panic("hostgen: enumDesc of " + s.String())
	}
	return g.addDesc("enum|"+spec, spec, "")
}

func (g *Generator) tupleDesc(slots []rt.SlotType) string {
	parts := make([]string, len(slots))
	for i, s := range slots {
		parts[i] = slotExpr(s)
	}
	expr := "rt.TupleDesc(" + strings.Join(parts, ", ") + ")"
	return g.addDesc("tuple|"+expr, "", expr)
}

func slotExpr(s rt.SlotType) string {
	return map[rt.SlotType]string{
		rt.SlotRef: "rt.SlotRef", rt.SlotInt: "rt.SlotInt", rt.SlotFloat: "rt.SlotFloat", rt.SlotBool: "rt.SlotBool",
		rt.SlotByte: "rt.SlotByte", rt.SlotString: "rt.SlotString", rt.SlotBytes: "rt.SlotBytes",
	}[s]
}

func fieldSlots(s *Shape) []rt.SlotType {
	out := make([]rt.SlotType, len(s.Fields))
	for i, f := range s.Fields {
		out[i] = f.Shape.Slot()
	}
	return out
}

// layoutOffsets is rt's layout rule: each field's offset within its bank, in
// field order.
func layoutOffsets(slots []rt.SlotType) []int {
	var nw, ns, nr int
	out := make([]int, len(slots))
	for i, s := range slots {
		switch s.Bank() {
		case rt.BankWord:
			out[i] = nw
			nw++
		case rt.BankStr:
			out[i] = ns
			ns++
		default:
			out[i] = nr
			nr++
		}
	}
	return out
}

func shapeKey(s *Shape) string {
	switch s.Kind {
	case SStruct, SDistinct, SHost, SEnum:
		return fmt.Sprintf("%d:%s", s.Kind, s.Name)
	}
	parts := make([]string, len(s.Elems))
	for i, e := range s.Elems {
		parts[i] = shapeKey(e)
	}
	k := fmt.Sprintf("%d(%s)", s.Kind, strings.Join(parts, ","))
	if s.Ret != nil {
		k += "->" + shapeKey(s.Ret)
	}
	return k
}

// --- Go types ----------------------------------------------------------------

type goField struct {
	path string // selector path from the struct value, `A.B`
	typ  Type
}

// goFields is the marshaller's field walk: exported fields, embedded structs
// flattened, `nomi:"name"` and `nomi:"-"` tags, snake_case otherwise.
func goFields(t Type) (map[string]goField, error) {
	out := map[string]goField{}
	var walk func(t Type, prefix string) error
	walk = func(t Type, prefix string) error {
		for i := range t.NumField() {
			f := t.Field(i)
			if !f.Exported {
				continue
			}
			if f.Anonymous && f.Type.Kind() == reflect.Struct {
				if err := walk(f.Type, prefix+f.Name+"."); err != nil {
					return err
				}
				continue
			}
			tag := f.Tag.Get("nomi")
			if tag == "-" {
				continue
			}
			name := tag
			if name == "" {
				name = strcase.ToSnake(f.Name)
			}
			if _, dup := out[name]; dup {
				return fmt.Errorf("embedded struct field %q collides with outer field", name)
			}
			out[name] = goField{path: prefix + f.Name, typ: f.Type}
		}
		return nil
	}
	return out, walk(t, "")
}

// sameFields requires the Go struct to carry exactly the declared fields. The
// marshaller builds a record from whatever the Go struct has; a generated
// adapter writes the declared layout, so a drift between the two is refused
// here, at generation, rather than producing a record the declaration does not
// describe.
func sameFields(s *Shape, fields map[string]goField) error {
	declared := map[string]bool{}
	for _, f := range s.Fields {
		declared[f.Name] = true
		if _, ok := fields[f.Name]; !ok {
			return fmt.Errorf("%s declares field %s and the Go struct has no field projecting to it", s.Name, f.Name)
		}
	}
	for name := range fields {
		if !declared[name] {
			return fmt.Errorf("the Go struct has field %s and %s declares none", name, s.Name)
		}
	}
	return nil
}

// typ spells a Go type in the generated file, importing its package.
func (g *Generator) typ(t Type) (string, error) {
	if base, args, ok := rtGenericArgs(t); ok {
		spelled := make([]string, len(args))
		for i, a := range args {
			s, err := g.typ(a)
			if err != nil {
				return "", err
			}
			spelled[i] = s
		}
		return "rt." + base + "[" + strings.Join(spelled, ", ") + "]", nil
	}
	if t.Name() != "" {
		if strings.ContainsAny(t.Name(), "[]") {
			return "", fmt.Errorf("Go %s is a generic instantiation; the generator does not spell those", t)
		}
		if t.PkgPath() == "" || (g.ownPkg != "" && t.PkgPath() == g.ownPkg) {
			return t.Name(), nil
		}
		return g.alias(t.PkgPath()) + "." + t.Name(), nil
	}
	switch t.Kind() {
	case reflect.Pointer:
		e, err := g.typ(t.Elem())
		return "*" + e, err
	case reflect.Slice:
		e, err := g.typ(t.Elem())
		return "[]" + e, err
	case reflect.Map:
		k, err := g.typ(t.Key())
		if err != nil {
			return "", err
		}
		v, err := g.typ(t.Elem())
		return "map[" + k + "]" + v, err
	case reflect.Func:
		in := make([]string, t.NumIn())
		for i := range t.NumIn() {
			s, err := g.typ(t.In(i))
			if err != nil {
				return "", err
			}
			in[i] = s
		}
		out := make([]string, t.NumOut())
		for i := range t.NumOut() {
			s, err := g.typ(t.Out(i))
			if err != nil {
				return "", err
			}
			out[i] = s
		}
		sig := "func(" + strings.Join(in, ", ") + ")"
		switch len(out) {
		case 0:
		case 1:
			sig += " " + out[0]
		default:
			sig += " (" + strings.Join(out, ", ") + ")"
		}
		return sig, nil
	}
	return "", fmt.Errorf("Go %s has no spelling the generator writes", t)
}

func (g *Generator) alias(pkgPath string) string {
	if a, ok := g.imports[pkgPath]; ok {
		return a
	}
	base := path.Base(pkgPath)
	a := base
	for i := 2; g.taken[a]; i++ {
		a = fmt.Sprintf("%s%d", base, i)
	}
	g.taken[a] = true
	g.imports[pkgPath] = a
	return a
}

// funcName spells the Go function a binding holds, read off the linked
// symbol so the generated call cannot disagree with the table.
func (g *Generator) funcName(fv reflect.Value) (string, error) {
	f := runtime.FuncForPC(fv.Pointer())
	if f == nil {
		return "", fmt.Errorf("the function value has no symbol")
	}
	full := f.Name() // nomi/stdregex.FFICompile
	slash := strings.LastIndex(full, "/")
	dot := strings.Index(full[slash+1:], ".")
	if dot < 0 {
		return "", fmt.Errorf("symbol %q has no package qualifier", full)
	}
	pkg, sym := full[:slash+1+dot], full[slash+1+dot+1:]
	if strings.ContainsAny(sym, ".[]") || strings.HasPrefix(sym, "func") {
		return "", fmt.Errorf("symbol %q is not a top-level function; a closure or method value cannot be called by name", full)
	}
	return g.alias(pkg) + "." + sym, nil
}

func (g *Generator) fresh(prefix string) string {
	g.next++
	return fmt.Sprintf("%s%d", prefix, g.next)
}

// paramList renders a declaration's parameters for the adapter's comment.
func paramList(d *ast.ExternFunc) string {
	parts := make([]string, len(d.Params))
	for i, p := range d.Params {
		t := "?"
		if p.TypeAnnotation != nil {
			t = p.TypeAnnotation.TypeString()
		}
		parts[i] = p.Name + ": " + t
	}
	return strings.Join(parts, ", ")
}
