[language-server.nomi-lsp]
command = "nomi-lsp"

[[language]]
name = "nomi"
language-id = "nomi"
scope = "source.nomi"
injection-regex = "nomi"
file-types = ["nomi"]
roots = ["nomi.toml", "go.mod", ".git"]
comment-tokens = ["//", "///", "//!"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "nomi", args = ["fmt"] }
language-servers = ["nomi-lsp"]

[[grammar]]
name = "nomi"
source = { git = "https://github.com/nomi-language/tree-sitter-nomi", rev = "13ef7979a5096d45ddce3d735e50380babfe4334" }
