[language-server.nomi-lsp]
command = "nomi-lsp"

[[language]]
name = "nomi"
language-id = "nomi"
scope = "source.nomi"
injection-regex = "nomi"
file-types = ["nomi"]
shebangs = ["nomi"]
roots = ["nomi.toml", "go.mod", ".git"]
comment-tokens = ["//", "///", "//!"]
indent = { tab-width = 4, unit = "    " }
text-width = 100
formatter = { command = "nomi", args = ["fmt"] }
language-servers = ["nomi-lsp"]

[[grammar]]
name = "nomi"
source = { git = "https://github.com/nomi-language/tree-sitter-nomi", rev = "4513638689ca3ee4b8c846f9c01f5002aeaaf4af" }
