#!/usr/bin/env bash
# Regenerate, build, and install Neovim support for Nomi (editors/nvim/).
#
#   scripts/sync-nvim-runtime.sh               regenerate editors/nvim/queries/nomi/*.scm
#   scripts/sync-nvim-runtime.sh --parser DIR  compile the parser to DIR/nomi.so (no query regeneration)
#   scripts/sync-nvim-runtime.sh --install     regenerate, then copy the plugin and a freshly
#                                              compiled parser into
#                                              ${XDG_DATA_HOME:-~/.local/share}/nvim/site/pack/nomi/start/nomi
#
# The queries are GENERATED. Do not edit editors/nvim/queries/nomi/*.scm by hand:
#   highlights.scm   from editors/zed/languages/nomi/highlights.scm (last-wins order,
#                    which Neovim also uses), with captures renamed to Neovim's
#                    standard groups (:help treesitter-highlight-groups)
#   injections.scm   byte-identical copy of tree-sitter-nomi/queries/injections.scm
#   locals.scm, folds.scm, indents.scm, textobjects.scm
#                    from editors/helix/runtime/queries/nomi/, with captures renamed
#                    to Neovim / nvim-treesitter / nvim-treesitter-textobjects names
#
# Every rename asserts that its source text is still present, and every capture
# in the output is checked against the names Neovim and the two nvim-treesitter
# plugins recognise, so a drifted source query fails this script instead of
# producing a silently wrong copy.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NVIM_NOMI="$ROOT/editors/nvim"
QUERY_DIR="$NVIM_NOMI/queries/nomi"
GRAMMAR="$ROOT/tree-sitter-nomi"

generate_queries() {
  mkdir -p "$QUERY_DIR"
  cp "$GRAMMAR/queries/injections.scm" "$QUERY_DIR/injections.scm"
  python3 - "$ROOT" "$QUERY_DIR" <<'PY'
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])
zed = root / "editors/zed/languages/nomi/highlights.scm"
helix = root / "editors/helix/runtime/queries/nomi"


def fail(msg):
    sys.exit(f"sync-nvim-runtime: {msg}")


def must_replace(text, old, new, source, count=None):
    n = text.count(old)
    if n == 0 or (count is not None and n != count):
        fail(f"{source}: expected {count or 'some'} occurrence(s) of {old!r}, found {n}; update the generator")
    return text.replace(old, new)


def must_sub(text, pattern, repl, source):
    new, n = re.subn(pattern, repl, text)
    if n == 0:
        fail(f"{source}: pattern {pattern!r} matched nothing; update the generator")
    return new


def header(source):
    return (
        f"; GENERATED by scripts/sync-nvim-runtime.sh from {source}.\n"
        "; Do not edit; change the source and run `make build-nvim`.\n\n"
    )


# --- highlights.scm -------------------------------------------------------
src = "editors/zed/languages/nomi/highlights.scm"
text = zed.read_text()

# Zed's and Helix's attached-test dim patterns are left out: the plugin dims
# `//!` tests from Lua (lua/nomi/attached_tests.lua), above semantic tokens
# and with the block under the cursor shown normally, which a query capture
# cannot do.
text = must_sub(
    text,
    r"(?s)\n; BEGIN attached-test dim .*?\n; END attached-test dim\n",
    "",
    src,
)
if "(attached_test_prompt" in text:
    fail(f"{src}: an attached_test_prompt capture survived outside the dim block; update the generator")

# Anonymous keyword tokens -> Neovim's keyword subgroups. Tokens not listed
# stay plain @keyword. The lookbehind is the literal token, so the same token
# is renamed wherever it appears (e.g. `"fn"` in every function declaration).
keyword_groups = {
    "keyword.function": ["fn"],
    "keyword.type": ["type", "struct", "enum", "typealias", "interface", "impl"],
    "keyword.import": ["import", "as", "export", "gopkg"],
    "keyword.conditional": ["if", "else", "case", "when"],
    "keyword.repeat": ["break"],
    "keyword.return": ["return"],
    "keyword.operator": ["and", "or"],
    "keyword.modifier": ["opaque", "once", "extern"],
    "keyword.exception": ["try"],
    "keyword.coroutine": ["concurrent"],
    "keyword.debug": ["dbg"],
}
for group, tokens in keyword_groups.items():
    for tok in tokens:
        text = must_sub(text, rf'(?<="{re.escape(tok)}" )@keyword(?![\w.])', "@" + group, src)

# Named keyword nodes.
for node, group in [
    ("(continue_statement)", "keyword.repeat"),
    ("(pub)", "keyword.modifier"),
    ("(host_keyword)", "keyword.modifier"),
]:
    text = must_sub(text, rf"(?<={re.escape(node)} )@keyword(?![\w.])", "@" + group, src)

text = must_sub(text, r'(?<="true" )@constant\.builtin(?![\w.])', "@boolean", src)
text = must_sub(text, r'(?<="false" )@constant\.builtin(?![\w.])', "@boolean", src)
text = must_replace(text, "(float) @number\n", "(float) @number.float\n", src, 1)
text = must_replace(text, "(decimal) @number\n", "(decimal) @number.float\n", src, 1)
text = must_replace(text, "(codepoint) @string.special\n", "(codepoint) @character\n", src, 1)
text = must_sub(text, r"@property(?![\w.])", "@variable.member", src)
text = must_replace(text, "@module.path_separator", "@punctuation.delimiter", src, 1)
text = must_replace(
    text,
    "(call_expression\n  . (identifier) @function)",
    "(call_expression\n  . (identifier) @function.call)",
    src,
    1,
)
text = must_replace(
    text,
    "(call_expression\n  . (field_access\n    (identifier) @function .))",
    "(call_expression\n  . (field_access\n    (identifier) @function.call .))",
    src,
    1,
)
text = text.replace("Zed's query priority", "Neovim's query priority")
text = text.replace("Zed's last-wins priority", "Neovim's last-wins priority")
text = text.replace("Zed layers semantic tokens", "editors layer semantic tokens")

text = header(src) + text.rstrip("\n") + """

; Neovim-only (added by the generator): the prelude's scalar types read as
; builtin types. Last so it wins over the generic @type captures above.
((type_identifier) @type.builtin
  (#any-of? @type.builtin "Bool" "Byte" "Bytes" "Decimal" "Float" "Int" "String" "Unit"))
"""
(out / "highlights.scm").write_text(text)

# --- locals.scm -----------------------------------------------------------
src = "editors/helix/runtime/queries/nomi/locals.scm"
text = (helix / "locals.scm").read_text()
# Helix's locals dim block exists only because Helix recolours references by
# their definitions; Neovim dims attached tests from Lua.
text = must_sub(
    text,
    r"(?s); BEGIN attached-test dim .*?\n; END attached-test dim\n\n",
    "",
    src,
)
if "attached_test_prompt" in text:
    fail(f"{src}: an attached_test_prompt pattern survived outside the dim block; update the generator")
text = must_replace(text, "@local.definition.variable.parameter", "@local.definition.parameter", src)
text = must_sub(text, r"@local\.definition\.variable(?![\w.])", "@local.definition.var", src)
(out / "locals.scm").write_text(header(src) + text)

# --- folds.scm (same capture vocabulary) ----------------------------------
src = "editors/helix/runtime/queries/nomi/folds.scm"
(out / "folds.scm").write_text(header(src) + (helix / "folds.scm").read_text())

# --- indents.scm (nvim-treesitter's indentexpr) -----------------------------
src = "editors/helix/runtime/queries/nomi/indents.scm"
text = (helix / "indents.scm").read_text()
text = must_sub(text, r"\] @indent(?![\w.])", "] @indent.begin", src)
# A closing bracket both ends the block (for the line after it) and dedents
# the line it starts, which is nvim-treesitter's convention for brackets.
text = must_sub(text, r"@outdent(?![\w.])", "@indent.end @indent.branch", src)
# Helix's @extend keeps a continued arm's following lines inside the arm.
# nvim-treesitter's equivalent is to open an indent at a multi-line arm.
text = must_sub(text, r"\((case_branch|else_arm)\) @extend(?![\w.])", r"(\1) @indent.begin", src)
(out / "indents.scm").write_text(header(src) + text)

# --- textobjects.scm (nvim-treesitter-textobjects) --------------------------
src = "editors/helix/runtime/queries/nomi/textobjects.scm"
text = (helix / "textobjects.scm").read_text()
# nvim-treesitter-textobjects has no test object: a test case is a function,
# a `tests` group is a class.
text = must_replace(
    text,
    "(test_declaration\n  (body)? @test.inside) @test.around",
    "(test_declaration\n  (body)? @function.inside) @function.around",
    src,
    1,
)
text = must_replace(
    text,
    "(tests_declaration\n  (tests_body)? @test.inside) @test.around",
    "(tests_declaration\n  (tests_body)? @class.inside) @class.around",
    src,
    1,
)
# ...and no entry object: list elements, construction fields and variants are
# exposed as parameters, the nearest standard object.
text = must_sub(text, r"@entry\.", "@parameter.", src)
text = must_sub(text, r"(@[\w.]+)\.inside(?![\w.])", r"\1.inner", src)
text = must_sub(text, r"(@[\w.]+)\.around(?![\w.])", r"\1.outer", src)
text = text.replace("`]e` walks", "the parameter motions walk")
(out / "textobjects.scm").write_text(header(src) + text)

# --- capture check ----------------------------------------------------------
# Highlight groups: :help treesitter-highlight-groups (Neovim 0.11).
highlight_groups = set("""
variable variable.builtin variable.parameter variable.parameter.builtin
variable.member constant constant.builtin constant.macro module module.builtin
label string string.documentation string.regexp string.escape string.special
string.special.symbol string.special.path string.special.url character
character.special boolean number number.float type type.builtin
type.definition attribute attribute.builtin property function
function.builtin function.call function.macro function.method
function.method.call constructor operator keyword keyword.coroutine
keyword.function keyword.operator keyword.import keyword.type
keyword.modifier keyword.repeat keyword.return keyword.debug
keyword.exception keyword.conditional keyword.conditional.ternary
keyword.directive keyword.directive.define punctuation.delimiter
punctuation.bracket punctuation.special comment comment.documentation
comment.error comment.warning comment.todo comment.note tag tag.builtin
tag.attribute tag.delimiter spell nospell conceal none
""".split())
textobjects = set()
for obj in ["assignment", "attribute", "block", "call", "class", "comment",
            "conditional", "frame", "function", "loop", "parameter", "regex",
            "return"]:
    textobjects |= {f"{obj}.inner", f"{obj}.outer"}
textobjects |= {"assignment.lhs", "assignment.rhs", "number.inner",
                "scopename.inner", "statement.outer"}
allowed = {
    "highlights.scm": highlight_groups,
    # `@tag` is a helper capture read only by the #eq?/#not-eq? predicates.
    "injections.scm": {"injection.content", "injection.language", "tag"},
    "locals.scm": {"local.scope", "local.reference"} | {
        "local.definition." + k for k in
        ["var", "parameter", "function", "method", "type", "field", "import",
         "namespace", "constant", "macro", "enum", "associated"]},
    "folds.scm": {"fold"},
    "indents.scm": {"indent." + k for k in
                    ["begin", "end", "branch", "dedent", "align", "zero", "auto", "ignore"]},
    "textobjects.scm": textobjects,
}
capture = re.compile(r"@([A-Za-z_][\w.]*)")
bad = []
for name, ok in allowed.items():
    for lineno, line in enumerate((out / name).read_text().splitlines(), 1):
        # Blank string literals (so `"@"` and `";"` tokens are not read as
        # captures or comments), then drop the comment.
        code = re.sub(r'"(?:[^"\\]|\\.)*"', '""', line).split(";", 1)[0]
        for cap in capture.findall(code):
            if cap.startswith("_") or cap in ok:
                continue
            bad.append(f"{name}:{lineno}: @{cap}")
if bad:
    fail("captures Neovim does not recognise:\n  " + "\n  ".join(bad))
PY
}

compile_parser() {
  local dest="$1"
  local tmp
  mkdir -p "$dest"
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/nomi-nvim-parser.XXXXXX")"
  local sources=("$GRAMMAR/src/parser.c")
  if [[ -f "$GRAMMAR/src/scanner.c" ]]; then
    sources+=("$GRAMMAR/src/scanner.c")
  fi
  cc -shared -fPIC -O2 -I "$GRAMMAR/src" "${sources[@]}" -o "$tmp/nomi.so"
  # Rename into place rather than overwrite: a running Neovim has the old
  # library mapped, and rewriting it in place can crash that process.
  mv -f "$tmp/nomi.so" "$dest/nomi.so"
  rmdir "$tmp"
  echo "Built $dest/nomi.so"
}

case "${1:-}" in
  "")
    generate_queries
    echo "Synced Neovim Nomi queries in $QUERY_DIR"
    ;;
  --parser)
    [[ -n "${2:-}" ]] || { echo "usage: $0 --parser DIR" >&2; exit 2; }
    compile_parser "$2"
    ;;
  --install)
    generate_queries
    data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
    pack="$data_home/nvim/site/pack/nomi/start/nomi"
    rm -rf "$pack"
    mkdir -p "$pack"
    cp -R "$NVIM_NOMI/ftdetect" "$NVIM_NOMI/ftplugin" "$NVIM_NOMI/lsp" \
      "$NVIM_NOMI/lua" "$NVIM_NOMI/plugin" "$NVIM_NOMI/queries" "$NVIM_NOMI/README.md" "$pack/"
    compile_parser "$pack/parser"
    echo "Installed Nomi Neovim support into $pack"
    ;;
  *)
    echo "usage: $0 [--parser DIR | --install]" >&2
    exit 2
    ;;
esac
