package ffirun

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	goformat "go/format"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

// wrapperTemplate is the canonical Go source the codegen stage
// emits. It uses only public packages: nomi/vmhost for its three modes
// (check, vmrun, vmtest), with a host table of adapters generated from the
// project's `go` bindings.
//
// The header carries a hash of the template text itself (computed in
// init via SHA256(wrapperTemplate)[0:12]). This hash is recorded in
// the cache's hash.json and used to invalidate the cached wrapper
// when the `nomi` binary is upgraded and ships a new template. The
// header comment doesn't affect compilation; it's a forensic aid
// when staring at a stale wrapper in the cache.
//
// Stable ordering: the Packages range is fed a slice that was sorted
// at discovery time. Combined with deterministic alias assignment,
// the wrapper output is byte-for-byte reproducible across runs given
// the same input — the property the golden test pins down.
const wrapperTemplate = `// Code generated by nomi — DO NOT EDIT.
// Wrapper template hash: {{.TemplateHash}}
// Wrapper module imports project-local FFI through go.mod replace.
// Source project: {{.ProjectPath}}
package main

import (
	stdfmt "fmt"
	stdos "os"
{{- if .HasEntryScopedKeys}}
	stdfilepath "path/filepath"
{{- end}}
{{- if not .Runner}}
	stdstrconv "strconv"
{{- end}}

{{range .Packages}}{{if wrapperImports .}}	{{.Alias}} "{{.ImportPath}}"
{{end}}{{end}}{{if .UsesStdTime}}	stdtime "time"

{{end}}{{if .Runner}}	nomivmrunner "github.com/nomi-language/nomi/vmrunner"
{{- if .Compiler}}
	nomivmrunnercompiler "github.com/nomi-language/nomi/vmrunner/compiler"
{{- end}}
{{- else}}	stdcontext "context"
	nomivmhost "github.com/nomi-language/nomi/vmhost"
{{- end}}
{{- range .Adapters.Imports}}
	{{.Alias}} "{{.Path}}"
{{- end}}
)

{{if not .Runner}}
const ffiTestResultMarker = "__NOMI_FFI_TEST_RESULT"
const imageUsesCompilerMarker = "__NOMI_IMAGE_USES_COMPILER"
const wrapperModeFlag = "--nomi-wrapper-mode"
{{end}}
{{if .HasInlineGo}}
{{range .InlineGoHelpers}}
{{.Signature}} {
	{{.Body}}
}
{{end}}
{{end}}
{{if .HasGoDecls}}
{{range .Packages}}{{range .GoDecls}}
{{.}}

{{end}}{{end}}{{end}}{{range .Packages}}{{range .Exports}}{{if .GoBody}}
func {{.WrapperName}}({{.ParamDecls}}){{returnSuffix .ReturnDecl}} {
{{inlineGoBody .SourceFile .SourceLine .GoBody}}
}

{{end}}{{end}}{{end}}
{{if .Runner}}
// main is the project's runner: the program 'nomi build' appended to this
// executable, run on the VM with the adapters generated below.
func main() {
	nomivmrunner.Main(nomivmrunner.WithEntryHosts(func(entry string) nomivmrunner.HostTable {
		return nomiHostTable(entry)
	}){{if .Compiler}}, nomivmrunner.WithCompiler(nomivmrunnercompiler.Table){{end}})
}

// The wrapper's own modes use these; the runner has none.
var (
	_ = stdfmt.Sprint
	_ = stdos.Exit
)
{{else}}
func main() {
	mode := ""
	targetPath := ""
	extraArgs := []string{}
	if len(stdos.Args) >= 4 && stdos.Args[1] == wrapperModeFlag {
		mode = stdos.Args[2]
		targetPath = stdos.Args[3]
		extraArgs = stdos.Args[4:]
		stdos.Args = []string{stdos.Args[0]}
	}
	if mode == "" || targetPath == "" {
		stdfmt.Fprintln(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode <check|vmrun|vmtest> <entry.nomi> [line]")
		stdos.Exit(1)
	}
	// ffirun launches the compiled wrapper from WrapperDir so every mode starts
	// from the same generated environment. The USER expects their original cwd
	// to survive (relative file paths in user code, e.g. sqlite.open("tasks.db"),
	// should resolve where they ran nomi, not in the FFI build cache). Restore it
	// from the env var ffirun set before any user code reaches os.Getwd.
	if cwd := stdos.Getenv("NOMI_FFIRUN_USER_CWD"); cwd != "" {
		if err := stdos.Chdir(cwd); err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi %s: restoring user cwd %q: %v\n", mode, cwd, err)
			stdos.Exit(1)
		}
	}
	// 'nomi test --format json' passes the format after the line. Its stdout
	// carries only report records, so a test's own output goes to stderr.
	testFormat := nomivmhost.TestFormatText
	if mode == "vmtest" && len(extraArgs) > 1 {
		format, err := nomivmhost.ParseTestFormat(extraArgs[1])
		if err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi test: %v\n", err)
			stdos.Exit(1)
		}
		testFormat = format
	}
	switch mode {
	case "check":
		checkProgramVM(targetPath)
	case "vmrun":
		runProgramVM(targetPath, extraArgs)
	case "vmtest":
		runTestFileVM(targetPath, extraArgs, testFormat)
	case "vmimage":
		buildImageVM(targetPath, extraArgs)
	default:
		stdfmt.Fprintf(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode <check|vmrun|vmtest> <entry.nomi> [line]\n")
		stdos.Exit(1)
	}
}
{{end}}
// The Go symbols the project binds, referenced here so the Go compiler checks
// each one exists (and reports a missing one at its Nomi declaration) whether
// or not the adapter generator could adapt it.
var (
{{range .Packages}}{{ $pkg := . }}{{range .Types}}{{lineDirective .SourceFile .SourceLine}}
	_ = {{typePrototype $pkg .}}
{{end}}{{range .Exports}}{{lineDirective .SourceFile .SourceLine}}
	_ = {{funcValue $pkg .}}
{{end}}{{end}})
{{if not .Runner}}
// checkProgramVM, runProgramVM and runTestFileVM are the wrapper's modes: nomi
// check's, nomi run's and nomi test's. The VM calls the project's bindings
// through the adapters generated below (nomiHostTable).
func checkProgramVM(entryPath string) {
	if err := nomivmhost.Check(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath))); err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
}

func runProgramVM(entryPath string, args []string) {
	p, err := nomivmhost.Load(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath)), nomivmhost.WithInput(stdos.Stdin))
	if err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
	if err := p.RequireMain("run"); err != nil {
		stdfmt.Fprintf(stdos.Stderr, "nomi run: %v\n", err)
		stdos.Exit(1)
	}
	if err := p.Run(stdcontext.Background(), stdos.Stdout, args, true); err != nil {
		if blocked, ok := nomivmhost.IsBlocked(err); ok {
			blocked.Write(stdos.Stderr, nomivmhost.DisplayPath(entryPath))
		} else {
			nomivmhost.WriteFailure(stdos.Stderr, err)
		}
		stdos.Exit(1)
	}
}

// buildImageVM is nomi build's half of the wrapper: lower the entry with the
// project's bindings and write its IR image to args[0], or report what
// nomi run would report and write nothing.
func buildImageVM(entryPath string, args []string) {
	if len(args) < 1 {
		stdfmt.Fprintln(stdos.Stderr, "usage: nomi-ffi-wrapper --nomi-wrapper-mode vmimage <entry.nomi> <image>")
		stdos.Exit(1)
	}
	p, err := nomivmhost.Load(entryPath, nomivmhost.WithHosts(nomiHostTable(entryPath)))
	if err != nil {
		nomivmhost.WriteFailure(stdos.Stderr, err)
		stdos.Exit(1)
	}
	image, usesCompiler, err := p.BuildImage()
	if err != nil {
		if blocked, ok := nomivmhost.IsBlocked(err); ok {
			blocked.Write(stdos.Stderr, nomivmhost.DisplayPath(entryPath))
		} else {
			stdfmt.Fprintln(stdos.Stderr, err)
		}
		stdos.Exit(1)
	}
	if err := stdos.WriteFile(args[0], image, 0o644); err != nil {
		stdfmt.Fprintln(stdos.Stderr, err)
		stdos.Exit(1)
	}
	if usesCompiler {
		stdfmt.Println(imageUsesCompilerMarker)
	}
}

func runTestFileVM(testPath string, args []string, format nomivmhost.TestFormat) {
	opts := nomivmhost.TestOptions{}
	if len(args) > 0 && args[0] != "" {
		line, err := stdstrconv.Atoi(args[0])
		if err != nil {
			stdfmt.Fprintf(stdos.Stderr, "nomi test: invalid line %q\n", args[0])
			stdfmt.Printf("%s %d %d %d\n", ffiTestResultMarker, 0, 1, 0)
			stdos.Exit(1)
		}
		opts.Line = line
		opts.LineSet = true
	}
	rep := nomivmhost.NewTestReportFormat(stdos.Stdout, format)
	// In json mode stdout carries only records, so a case's own output goes
	// to stderr.
	out := stdos.Stdout
	if format == nomivmhost.TestFormatJSON {
		out = stdos.Stderr
	}
	p, err := nomivmhost.Load(testPath, nomivmhost.WithHosts(nomiHostTable(testPath)))
	if err != nil {
		rep.FailFile(testPath, err)
	} else {
		p.Test(out, rep, testPath, opts, func(name string) string { return nomivmhost.TestName(testPath, name) })
	}
	passed, failed := rep.Counts()
	blocked := rep.BlockedCount()
	stdfmt.Printf("%s %d %d %d\n", ffiTestResultMarker, passed, failed, blocked)
	if failed > 0 || blocked > 0 {
		stdos.Exit(1)
	}
}
{{end}}
{{.Adapters.Decls}}
// nomiHostTable is the VM host table of this wrapper's bindings: the
// generated adapters, each keyed as the program at targetPath crosses under
// it.
func nomiHostTable(targetPath string) func(*hostadapt.Env) (map[string]hostadapt.Func, error) {
	return func(env *hostadapt.Env) (map[string]hostadapt.Func, error) {
		funcs, err := nomiHostBind(env)
		if err != nil {
			return nil, err
		}
{{- range .Adapters.Rekeyed}}
		if f, ok := funcs[{{quote .Key}}]; ok {
			if k := nomiExternKey(targetPath, {{quote .Key}}, {{quote .EntryKey}}, {{quote .SourceFile}}); k != {{quote .Key}} {
				delete(funcs, {{quote .Key}})
				funcs[k] = f
			}
		}
{{- end}}
{{- range .Adapters.Refused}}
		funcs[{{quote .Key}}] = func(*rt.Frame, []rt.Value) (rt.Value, error) {
			return nil, errors.New({{quote .Message}})
		}
{{- end}}
		return funcs, nil
	}
}

{{if .HasEntryScopedKeys}}
// nomiExternKey is the key one host declaration registers under FOR THIS LOAD,
// which is ONE key and not two.
//
// NOTE FOR AN EDITOR: this comment is inside a Go RAW STRING LITERAL (the
// wrapper template), so it must not contain a backtick. A backtick here
// terminates the literal and the file stops parsing several declarations
// later, which reads as an error in unrelated code.
//
// The runtime qualifies a non-entry file's host declarations with its module
// name and the ENTRY's with nothing, so 'ffi.nomi' declares 'ffi.echo_upper'
// when 'main.nomi' is the entry and 'echo_upper' when it is the entry itself.
// Discovery cannot know which file will be loaded — a project has many — so it
// emits both spellings and this function picks the one that applies.
//
// ONE key, chosen, rather than binding both: the program crosses under exactly
// one of them.
//
// entry is "" for a declaration whose key does not depend on the entry: an
// owner-qualified one ('impl Box { host fn … }') keys on the receiver type, and
// a file with no module name already has the entry's shape.
//
// Symlinks are resolved because the two paths reach here by different routes —
// one is an argument the user typed, the other came out of a filesystem walk.
// A resolution failure falls back to string equality, which is the same answer
// for every path with no symlink in it.
func nomiExternKey(target, module, entry, declared string) string {
	if entry == "" {
		return module
	}
	if target == declared {
		return entry
	}
	rt, terr := stdfilepath.EvalSymlinks(target)
	rd, derr := stdfilepath.EvalSymlinks(declared)
	if terr == nil && derr == nil && rt == rd {
		return entry
	}
	return module
}
{{end}}
`

// templateHash is SHA256(wrapperTemplate)[0:12] — the short version
// embedded in the wrapper header and recorded in hash.json. Computed
// once at init time.
var templateHash = computeTemplateHash()

func computeTemplateHash() string {
	sum := sha256.Sum256([]byte(wrapperTemplate))
	return hex.EncodeToString(sum[:])[:12]
}

// wrapperTmpl is the parsed template, ready for Execute. Parsing
// once at init time keeps codegen on the warm path branch-free.
var wrapperTmpl = template.Must(template.New("wrapper").Funcs(template.FuncMap{
	"funcValue":      wrapperFuncValue,
	"inlineGoBody":   inlineGoBody,
	"lineDirective":  inlineGoLineDirective,
	"quote":          strconv.Quote,
	"returnSuffix":   wrapperReturnSuffix,
	"typePrototype":  wrapperTypePrototype,
	"wrapperImports": wrapperImports,
}).Parse(wrapperTemplate))

// wrapperImports reports whether the generated wrapper must import pkg: every
// discovered package is a user's and its symbols are referenced below, so the
// only package left out is the empty import path a package of purely inline
// `go { }` bodies carries.
func wrapperImports(pkg DiscoveredPackage) bool {
	return pkg.ImportPath != ""
}

// renderWrapper executes the wrapper template with the supplied
// discovered packages and project path, returning the bytes of the
// generated main.go.
//
// The Packages slice is fed in DiscoveredPackage order; callers are
// responsible for having sorted/aliased it before calling. The
// template iterates in slice order, so input order determines output
// order — important for the golden test.
//
// renderWrapper is the bytes-only entry point used by the golden
// test. The cache stage (ensureWrapper, in cache.go) wraps it with
// filesystem I/O.
func renderWrapper(projectPath string, packages []DiscoveredPackage) ([]byte, error) {
	return renderMain(projectPath, packages, mainKind{})
}

// mainKind is which generated main package renderMain writes: the FFI
// wrapper (the zero value), or the project's `nomi build` runner, which
// links nomi/vmrunner instead of nomi/vmhost and so no front end, and
// std/compiler's hosts only when Compiler is set.
type mainKind struct {
	Runner   bool
	Compiler bool
}

func renderMain(projectPath string, packages []DiscoveredPackage, kind mainKind) ([]byte, error) {
	adapters, err := generateAdapters(projectPath, packages)
	if err != nil {
		return nil, fmt.Errorf("generating the VM's host adapters: %w", err)
	}
	data := struct {
		TemplateHash       string
		ProjectPath        string
		Packages           []DiscoveredPackage
		HasGoDecls         bool
		HasInlineGo        bool
		InlineGoHelpers    []InlineGoHelper
		UsesStdTime        bool
		HasEntryScopedKeys bool
		Adapters           *wrapperAdapters
		Runner             bool
		Compiler           bool
	}{
		Runner:             kind.Runner,
		Compiler:           kind.Compiler,
		TemplateHash:       templateHash,
		ProjectPath:        projectPath,
		Packages:           packages,
		HasGoDecls:         wrapperHasGoDecls(packages),
		HasInlineGo:        wrapperHasInlineGo(packages),
		InlineGoHelpers:    InlineGoHelpers,
		UsesStdTime:        wrapperUsesStdTime(packages),
		HasEntryScopedKeys: wrapperHasEntryScopedKeys(packages),
		Adapters:           adapters,
	}
	var buf bytes.Buffer
	if err := wrapperTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering wrapper template: %w", err)
	}
	out, err := goformat.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting wrapper source: %w", err)
	}
	return out, nil
}

// wrapperHasEntryScopedKeys reports whether any discovered declaration's key
// depends on which file is the entry, which is what decides whether the
// nomiExternKey helper is emitted at all.
//
// Gated so a wrapper with no module-qualified declaration carries no helper it
// never calls.
func wrapperHasEntryScopedKeys(packages []DiscoveredPackage) bool {
	for _, pkg := range packages {
		for _, t := range pkg.Types {
			if t.EntryKey != "" {
				return true
			}
		}
		for _, e := range pkg.Exports {
			if e.EntryKey != "" {
				return true
			}
		}
	}
	return false
}

func wrapperTypePrototype(pkg DiscoveredPackage, typ DiscoveredType) string {
	if typ.GoTypeExpr != "" {
		return "(" + typ.GoTypeExpr + ")(nil)"
	}
	return "(*" + pkg.Alias + "." + typ.TypeName + ")(nil)"
}

func wrapperFuncValue(pkg DiscoveredPackage, exp DiscoveredExport) string {
	if exp.GoBody != "" {
		return exp.WrapperName
	}
	return pkg.Alias + "." + exp.FuncName
}

func wrapperReturnSuffix(ret string) string {
	if ret == "" {
		return ""
	}
	return " " + ret
}

func inlineGoLineDirective(file string, line int) string {
	if file == "" || line <= 0 {
		return ""
	}
	return fmt.Sprintf("//line %s:%d", filepath.ToSlash(file), line)
}

func inlineGoBody(file string, line int, body string) string {
	body = indentGoBody(body)
	directive := inlineGoLineDirective(file, line)
	if directive == "" {
		return body
	}
	if body == "" {
		return directive
	}
	return directive + "\n" + body
}

func indentGoBody(body string) string {
	body = strings.TrimSpace(body)
	if body == "" {
		return ""
	}
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		lines[i] = "\t" + strings.TrimRight(line, " \t")
	}
	return strings.Join(lines, "\n")
}

func wrapperUsesStdTime(packages []DiscoveredPackage) bool {
	for _, pkg := range packages {
		for _, exp := range pkg.Exports {
			if strings.Contains(exp.ParamDecls, "stdtime.") || strings.Contains(exp.ReturnDecl, "stdtime.") {
				return true
			}
		}
	}
	return false
}

func wrapperHasGoDecls(packages []DiscoveredPackage) bool {
	for _, pkg := range packages {
		if len(pkg.GoDecls) > 0 {
			return true
		}
	}
	return false
}

func wrapperHasInlineGo(packages []DiscoveredPackage) bool {
	for _, pkg := range packages {
		for _, exp := range pkg.Exports {
			if exp.GoBody != "" {
				return true
			}
		}
	}
	return false
}
